import { useRef, useState, type PointerEvent } from 'react';
import { figmaAssets } from '../../assets/figmaAssets';

const advantages = [
  ['Pendidikan Berkualitas', 'Pembelajaran dirancang sesuai kompetensi keahlian dan kebutuhan dunia kerja.', figmaAssets.advantages.education],
  ['Terhubung dengan Dunia Industri', 'Membangun pengalaman belajar melalui kolaborasi dengan mitra industri.', figmaAssets.advantages.industry],
  ['Teaching Factory', 'Mengasah keterampilan melalui praktik dan pengalaman produksi nyata di lingkungan sekolah.', figmaAssets.advantages.blud],
  ['Pengalaman Karakter & Minat', 'Berkembang melalui organisasi, ekstrakurikuler, dan berbagai kegiatan siswa.', figmaAssets.advantages.interest],
  ['Lingkungan Belajar Inklusif', 'Ruang untuk belajar, berkarya, berkolaborasi, dan mengembangkan potensi setiap siswa.', figmaAssets.advantages.inclusive],
  ['Sertifikasi Kompetensi', 'Mengembangkan kompetensi siswa melalui skema sertifikasi yang relevan dengan bidang keahlian.', figmaAssets.advantages.lsp],
] as const;

export function SchoolAdvantages() {
  const [active, setActive] = useState(0);
  const [drag, setDrag] = useState(0);
  const start = useRef<number | null>(null);
  const move = (direction: number) => setActive((current) => Math.max(0, Math.min(advantages.length - 2, current + direction)));
  const down = (event: PointerEvent<HTMLDivElement>) => { start.current = event.clientX; event.currentTarget.setPointerCapture(event.pointerId); };
  const moving = (event: PointerEvent<HTMLDivElement>) => { if (start.current !== null) setDrag(event.clientX - start.current); };
  const up = (event: PointerEvent<HTMLDivElement>) => { if (start.current !== null && Math.abs(event.clientX - start.current) > 40) move(event.clientX < start.current ? 1 : -1); start.current = null; setDrag(0); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); };
  return <section className="relative mt-[88px] h-[645px] overflow-hidden bg-gradient-to-b from-soft-blue via-primary to-primary-dark py-0 text-white"><div className="absolute left-1/2 top-10 -translate-x-1/2"><span className="whitespace-nowrap rounded-full bg-[#f6fbff] px-3 py-[5px] text-sm font-semibold text-soft-blue shadow-sm">Keunggulan SMK Negeri 26 Jakarta</span></div><h2 className="absolute left-1/2 top-[103px] -translate-x-1/2 whitespace-nowrap text-center text-4xl font-bold drop-shadow-sm">Apa yang Membuat SMKN 26 Berbeda?</h2><div className="absolute left-1/2 top-[181px] flex h-[400px] w-[calc(100%-32px)] max-w-[1272px] -translate-x-1/2 cursor-grab touch-none select-none overflow-hidden active:cursor-grabbing" onPointerDown={down} onPointerMove={moving} onPointerUp={up} onPointerCancel={() => { start.current = null; setDrag(0); }}><div className="flex gap-6 transition-transform duration-300 ease-out" style={{ transform: `translateX(calc(-${active * 324}px - 170px + ${drag}px))`, transitionDuration: drag ? '0ms' : undefined }}>{advantages.map(([title, body, image]) => <article className="group relative flex h-[400px] w-[300px] shrink-0 flex-col justify-end overflow-hidden rounded-3xl bg-white p-[18px] text-ink shadow-lg transition hover:-translate-y-1 hover:shadow-2xl" key={title}><img className="absolute inset-x-0 top-0 h-[200px] w-full object-cover transition duration-300 group-hover:scale-105" src={image} alt="" /><span className="absolute left-3 top-[156px] grid size-[54px] place-items-center rounded-full bg-gradient-to-r from-primary-dark to-primary"><img className="size-[34px]" src={figmaAssets.advantages.secondaryEducationIcon} alt="" /></span><h3 className="relative text-2xl font-semibold leading-tight text-primary-dark">{title}</h3><p className="relative mt-1 text-xs leading-[18px]">{body}</p><a className="relative mt-3 inline-flex w-fit items-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-semibold text-primary transition hover:text-primary-dark" href="/information">Baca selengkapnya <img className="size-5" src={figmaAssets.icons.arrowRight} alt="" /></a></article>)}</div></div><button className="absolute left-[50px] top-[358px] z-20 grid size-12 select-none place-items-center rounded-full bg-white shadow-lg transition hover:scale-110" onPointerDown={(event) => event.stopPropagation()} onClick={() => move(-1)} aria-label="Keunggulan sebelumnya"><img className="size-6" src={figmaAssets.advantages.carouselLeft} alt="" /></button><button className="absolute right-[50px] top-[358px] z-20 grid size-12 select-none place-items-center rounded-full bg-white shadow-lg transition hover:scale-110" onPointerDown={(event) => event.stopPropagation()} onClick={() => move(1)} aria-label="Keunggulan berikutnya"><img className="size-6 rotate-180" src={figmaAssets.advantages.carouselRight} alt="" /></button></section>;
}
