export const figmaAssets = {
  branding: {
    schoolLogo: "/assets/figma/branding/smkn26-logo.png",
  },
  hero: {
    schoolBuilding: "/assets/figma/hero/hero-school-building.png",
    heroBackground: "/assets/figma/hero/hero-background.png",
    studentMale: "/assets/figma/hero/student-male.png",
    studentFemale: "/assets/figma/hero/student-female.png",
    headline: "/assets/figma/hero/hero-headline.svg",
  },
  icons: {
    search: "/assets/figma/icons/icon-search.svg",
    playVideo: "/assets/figma/icons/icon-play-video.svg",
    arrowRight: "/assets/figma/icons/icon-arrow-right.svg",
    chevronDown: "/assets/figma/icons/icon-chevron-down.svg",
  },
  shortcuts: {
    spmb: "/assets/figma/shortcuts/shortcut-spmb.png",
    library: "/assets/figma/shortcuts/shortcut-library.png",
    kjpPip: "/assets/figma/shortcuts/shortcut-kjp-pip.png",
    aiChat: "/assets/figma/shortcuts/shortcut-ai-chat.png",
  },
  school: {
    overviewPhoto: "/assets/figma/school/school-overview-photo-clean.png",
  },
  advantages: {
    education: "/assets/figma/advantages/advantage-education.png",
    secondaryEducationIcon:
      "/assets/figma/advantages/icon-book-education-secondary.svg",
    industry: "/assets/figma/advantages/advantage-industry.png",
    blud: "/assets/figma/advantages/advantage-blud.png",
    lsp: "/assets/figma/advantages/advantage-lsp.png",
    interest: "/assets/figma/advantages/advantage-interest.png",
    inclusive: "/assets/figma/advantages/advantage-inclusive.png",
    arrow: "/assets/figma/advantages/advantage-arrow.svg",
    carouselLeft: "/assets/figma/advantages/advantage-carousel-left.svg",
    carouselRight: "/assets/figma/advantages/advantage-carousel-right.svg",
  },
  partners: {
    azko: "/assets/figma/partners/partner-azko.png",
    pln: "/assets/figma/partners/partner-pln.png",
    toyota: "/assets/figma/partners/partner-toyota.png",
    wika: "/assets/figma/partners/partner-wika.png",
    panasonic: "/assets/figma/partners/partner-panasonic.png",
  },
  majors: {
    kgs: "/assets/figma/majors/major-kgs.png",
    tek: "/assets/figma/majors/major-tek.png",
    titl: "/assets/figma/majors/major-titl.png",
    tflm: "/assets/figma/majors/major-tflm.png",
    tkr: "/assets/figma/majors/major-tkr.png",
    sija: "/assets/figma/majors/major-sija.png",
    educationIcon: "/assets/figma/majors/icon-major-education.svg",
    arrowRight: "/assets/figma/majors/icon-arrow-right.svg",
    pointerLeft: "/assets/figma/majors/popover-pointer-left.svg",
    pointerRight: "/assets/figma/majors/popover-pointer-right.svg",
    backgroundShape: "/assets/figma/majors/major-background-shape.svg",
    badgeIcon: "/assets/figma/majors/icon-section-badge.svg",
  },
  videoProfile: {
    background: "/assets/figma/video-profile/video-profile-raw-02.jpg",
    playIdle: "/assets/figma/video-profile/video-profile-svg-01.svg",
    ringDefault: "/assets/figma/video-profile/video-profile-svg-03.svg",
    ringActive: "/assets/figma/video-profile/video-profile-svg-08.svg",
  },
  programs: {
    panels: [
      "/assets/figma/programs/programs-raw-01.png",
      "/assets/figma/programs/programs-raw-02.png",
      "/assets/figma/programs/programs-raw-03.png",
    ],
    cards: [
      "/assets/figma/programs/programs-raw-04.png",
      "/assets/figma/programs/programs-raw-05.png",
      "/assets/figma/programs/programs-raw-06.png",
    ],
  },
  blud: {
    icons: [
      "/assets/figma/blud/blud-svg-02.svg",
      "/assets/figma/blud/blud-TEK-icon.svg",
      "/assets/figma/blud/blud-TITL-icon.svg",
      "/assets/figma/blud/blud-TFLM-icon.svg",
      "/assets/figma/blud/blud-TKR-icon.svg",
      "/assets/figma/blud/blud-SIJA-icon.svg",
    ],
    shapes: [
      "/assets/figma/blud/blud-svg-01.svg",
      "/assets/figma/blud/blud-svg-03.svg",
      "/assets/figma/blud/blud-svg-05.svg",
      "/assets/figma/blud/blud-svg-07.svg",
      "/assets/figma/blud/blud-svg-09.svg",
      "/assets/figma/blud/blud-svg-11.svg",
    ],
  },
  achievements: [
    "/assets/figma/achievements/achievements-raw-01.png",
    "/assets/figma/achievements/achievements-raw-02.png",
    "/assets/figma/achievements/achievements-raw-03.png",
    "/assets/figma/achievements/achievements-raw-04.png",
    "/assets/figma/achievements/achievements-raw-05.png",
  ],
  news: [
    "/assets/figma/news/news-raw-01.png",
    "/assets/figma/news/news-raw-02.png",
    "/assets/figma/news/news-raw-03.png",
    "/assets/figma/news/news-raw-04.png",
    "/assets/figma/news/news-raw-05.png",
  ],
  aiCta: "/assets/figma/ai-cta/ai-cta-raw-01.png",
  aiCtaLayers: {
    fill: "/assets/figma/ai-cta/ai-cta-svg-07.svg",
    ring: "/assets/figma/ai-cta/ai-cta-svg-02.svg",
    outline: "/assets/figma/ai-cta/ai-cta-svg-10.svg",
    bot: "/assets/figma/ai-cta/ai-cta-raw-02.png",
  },
} as const;
