export const figmaAssets = {
  branding: {
    schoolLogo: "/assets/figma/branding/smkn26-logo.png",
  },
  hero: {
    schoolBuilding: "/assets/figma/hero/hero-school-building.png",
    heroBackground: "/assets/figma/hero/hero-background.png",
    studentMale: "/assets/figma/hero/student-male.png",
    studentFemale: "/assets/figma/hero/student-female.png",
    headline: "/assets/figma/hero/hero-headline.svg",
  },
  icons: {
    search: "/assets/figma/icons/icon-search.svg",
    playVideo: "/assets/figma/icons/icon-play-video.svg",
    arrowRight: "/assets/figma/icons/icon-arrow-right.svg",
    chevronDown: "/assets/figma/icons/icon-chevron-down.svg",
  },
  secondaryButton: {
    arrowRight: "/assets/figma/icons/secondary-arrow-right.svg",
  },
  shortcuts: {
    spmb: "/assets/figma/shortcuts/shortcut-spmb.png",
    library: "/assets/figma/shortcuts/shortcut-library.png",
    kjpPip: "/assets/figma/shortcuts/shortcut-kjp-pip.png",
    aiChat: "/assets/figma/shortcuts/shortcut-ai-chat.png",
  },
  school: {
    overviewPhoto: "/assets/figma/school/school-overview-photo-clean.png",
  },
  profile: {
    heroBackground: "/assets/figma/profile/profile-hero-bg.png",
    overviewPhoto: "/assets/figma/profile/profile-overview.png",
    overviewComposite: "/assets/figma/hero/mengenalsmkprofile.png",
    mottoBackground: "/assets/figma/profile/profile-motto-bg.png",
    semboyanBackground: "/assets/figma/profile/profile-semboyan-bg.png",
    marsBackground: "/assets/figma/profile/profile-mars-bg.png",
    mottoTitle: "/assets/figma/profile/motto.png",
    semboyanTitle: "/assets/figma/profile/semboyan.png",
    marsTitle: "/assets/figma/profile/Mars.png",
    marsHeroBackground: "/assets/figma/mars/belakangvidmars.png",
    marsHeroBallLeft: "/assets/figma/mars/bolabolaheromarskiri.png",
    marsHeroBallRight: "/assets/figma/mars/bolabolaheromarskecilkanan.png",
    creatorBuDerliana: "/assets/figma/mars/buderliana.png",
    creatorPakSutaryo: "/assets/figma/mars/pak sutaryo.png",
    timelineLine: "/assets/figma/profile/timelinegaris.png",
  },
  advantages: {
    education: "/assets/figma/advantages/advantage-education.png",
    secondaryEducationIcon:
      "/assets/figma/advantages/icon-book-education-secondary.svg",
    industry: "/assets/figma/advantages/advantage-industry.png",
    blud: "/assets/figma/advantages/advantage-blud.png",
    lsp: "/assets/figma/advantages/advantage-lsp.png",
    interest: "/assets/figma/advantages/advantage-interest.png",
    inclusive: "/assets/figma/advantages/advantage-inclusive.png",
    arrow: "/assets/figma/advantages/advantage-arrow.svg",
    carouselLeft: "/assets/figma/advantages/advantage-carousel-left.svg",
    carouselRight: "/assets/figma/advantages/advantage-carousel-right.svg",
  },
  partners: {
    pln: "/assets/figma/partners/partner-pln.png",
    wika: "/assets/figma/partners/partner-wika.png",
    panasonic: "/assets/figma/partners/partner-panasonic.png",
  },
  majors: {
    kgs: "/assets/figma/majors/major-kgs.png",
    tek: "/assets/figma/majors/major-tek.png",
    titl: "/assets/figma/majors/major-titl.png",
    tflm: "/assets/figma/majors/major-tflm.png",
    tkr: "/assets/figma/majors/major-tkr.png",
    sija: "/assets/figma/majors/major-sija.png",
    educationIcon: "/assets/figma/majors/icon-major-education.svg",
    arrowRight: "/assets/figma/majors/icon-arrow-right.svg",
    pointerLeft: "/assets/figma/majors/popover-pointer-left.svg",
    pointerRight: "/assets/figma/majors/popover-pointer-right.svg",
    backgroundShape: "/assets/figma/majors/major-background-shape.svg",
    badgeIcon: "/assets/figma/majors/icon-section-badge.svg",
  },
  videoProfile: {
    preview: "/assets/figma/video-profile/video-profile-preview.png",
    badgeIcon: "/assets/figma/video-profile/video-profile-badge-icon.svg",
    lowerShape: "/assets/figma/video-profile/video-profile-lower-shape.svg",
    playIcon: "/assets/figma/video-profile/video-profile-play-icon.svg",
    playRing: "/assets/figma/video-profile/video-profile-play-ring.svg",
    decorationLeft: "/assets/figma/video-profile/video-profile-decoration-left.svg",
    decorationRight: "/assets/figma/video-profile/video-profile-decoration-right.svg",
  },
  programs: {
    // Featured slider panels, in Figma slide order. Verified by reading the
    // artwork in each export: raw-04 marching band (slide 1 / default state),
    // raw-06 Tari, raw-03 Pencak Silat.
    panels: [
      "/assets/figma/programs/programs-raw-04.png",
      "/assets/figma/programs/programs-raw-06.png",
      "/assets/figma/programs/programs-raw-03.png",
    ],
    // Right-hand program cards: LSP, OSIS & MPK, BKK.
    cards: [
      "/assets/figma/programs/programs-raw-07.png",
      "/assets/figma/programs/programs-raw-10.png",
      "/assets/figma/programs/programs-raw-02.png",
    ],
  },
  blud: {
    badgeIcon: "/assets/figma/video-profile/video-profile-badge-icon.svg",
    icons: [
      "/assets/figma/blud/blud-svg-02.svg",
      "/assets/figma/blud/blud-TEK-icon.svg",
      "/assets/figma/blud/blud-TITL-icon.svg",
      "/assets/figma/blud/blud-TFLM-icon.svg",
      "/assets/figma/blud/blud-TKR-icon.svg",
      "/assets/figma/blud/blud-SIJA-icon.svg",
    ],
    defaultShapes: {
      kgs: "/assets/figma/blud/blud-KGS-shape.svg",
      tek: "/assets/figma/blud/blud-svg-06.svg",
      titl: "/assets/figma/blud/blud-svg-12.svg",
      tflm: "/assets/figma/blud/blud-svg-13.svg",
      tkr: "/assets/figma/blud/blud-TKR-shape.svg",
      sija: "/assets/figma/blud/blud-SIJA-shape.svg",
    },
    hoverShape: "/assets/figma/blud/blud-svg-19.svg",
  },
  achievements: {
    cards: [
      "/assets/figma/achievements/achievements-raw-08.png",
      "/assets/figma/achievements/achievements-raw-03.png",
      "/assets/figma/achievements/achievements-raw-01.png",
      "/assets/figma/achievements/achievements-raw-04.png",
      "/assets/figma/achievements/achievements-raw-07.png",
    ],
    detailArrow: "/assets/figma/achievements/achievements-svg-13.svg",
  },
  news: [
    "/assets/figma/news/news-raw-01.png",
    "/assets/figma/news/news-raw-02.png",
    "/assets/figma/news/news-raw-03.png",
    "/assets/figma/news/news-raw-04.png",
    "/assets/figma/news/news-raw-05.png",
  ],
  aiCta: "/assets/figma/ai-cta/ai-cta-raw-01.png",
  aiCtaLayers: {
    fill: "/assets/figma/ai-cta/ai-cta-svg-07.svg",
    ring: "/assets/figma/ai-cta/ai-cta-svg-02.svg",
    outline: "/assets/figma/ai-cta/ai-cta-svg-10.svg",
    bot: "/assets/figma/ai-cta/ai-cta-raw-02.png",
  },
} as const;
