import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";

type Config = { folder: string; name: string; code: string; color: string; hero: string; visual: string; flow: string; icon: string; whatsapp: string; stats: string[][]; intro: string; description: string; services: string[][]; projects: string[][]; docs: string[]; cta: string; ctaCopy: string };
const asset = (folder: string, name: string) => `/assets/figma/${folder}/${name}`;

const configs: Record<string, Config> = {
  manufaktur26: { folder: "BLUD-Manufaktur26", name: "Manufaktur26", code: "TFLM", color: "#d40009", hero: "Hero Section (6).png", visual: "image 4 (1).png", flow: "Alur BLUD (2).png", icon: "Button shortcut (5).png", whatsapp: "basil_whatsapp-solid (3).png", stats: [["140+", "Siswa Terlibat"], ["32+", "Client"], ["75+", "Project"], ["14+", "Jenis Layanan"]], intro: "Manufaktur26 merupakan unit produksi dan layanan berbasis kompetensi Teknik Fabrikasi Logam dan Manufaktur, yang dikelola oleh siswa untuk menerapkan keterampilan melalui proses produksi dan pekerjaan nyata.", description: "Di Manufaktur26, siswa tidak hanya mempelajari proses fabrikasi, tetapi juga belajar mengolah material, membentuk, memotong, dan menyambung material dengan mengutamakan ketelitian, disiplin, dan keselamatan kerja.", services: [["Fabrikasi Logam", "Pemasangan dan pengolahan material logam sesuai kebutuhan."], ["Pemotongan & Pembentukan", "Pengolahan material melalui proses pemotongan dan pembentukan."], ["Pengelasan", "Penerapan proses pengelasan untuk berbagai kebutuhan konstruksi."], ["Pengerjaan Komponen", "Pembuatan komponen melalui proses manufaktur yang terarah."]], projects: [["Fabrikasi Rangka Baja", "Fabrikasi Rangka Baja.png"], ["Pengelasan Konstruksi Logam", "Pengelasan Konstruksi Logam.png"], ["Pengeboran Komponen Mesin", "Pengeboran Komponen Mesin.png"], ["Pengukuran & Quality Control", "Pengukuran & Quality Control.png"]], docs: ["Dokumentasi Pembelajaran (5).png", "Dokumentasi Pembelajaran (6).png"], cta: "Punya Kebutuhan Fabrikasi?", ctaCopy: "Temukan solusi manufaktur bersama Manufaktur26 melalui kompetensi dan pengalaman nyata siswa TFLM." },
  garage26: { folder: "BLUD-Garage26", name: "Garage26", code: "TKR", color: "#666666", hero: "Hero Section (7).png", visual: "image 4 (2).png", flow: "Alur BLUD (3).png", icon: "Button shortcut (6).png", whatsapp: "basil_whatsapp-solid (4).png", stats: [["160+", "Siswa Terlibat"], ["45+", "Client"], ["120+", "Project"], ["18+", "Jenis Layanan"]], intro: "Garage26 adalah unit produksi dan layanan yang menjadi ruang bagi siswa Teknik Kendaraan Ringan untuk menerapkan kompetensi otomotif melalui pekerjaan dan proyek nyata.", description: "Di Garage26, siswa tidak hanya mempelajari perawatan kendaraan, tetapi juga belajar melakukan pemeriksaan, perbaikan, perawatan, hingga meningkatkan tampilan kendaraan.", services: [["Service Kendaraan", "Melakukan pemeriksaan dan perawatan kendaraan untuk menjaga performanya."], ["Perbaikan", "Menangani berbagai kebutuhan perbaikan dan penggantian komponen kendaraan."], ["Detailing & Coating", "Merawat dan meningkatkan tampilan kendaraan melalui proses detailing dan coating."], ["Pemeriksaan Kendaraan", "Memeriksa kondisi kendaraan untuk menemukan kebutuhan perawatan dan perbaikan."]], projects: [["Engine Tune-Up", "Engine Tune-Up.png"], ["Brake System Maintenance", "Brake System Maintenance.png"], ["Wheel & Tire Service", "Wheel & Tire Service.png"], ["Undercarriage Inspection", "Undercarriage Inspection.png"]], docs: ["Dokumentasi Pembelajaran (7).png", "Dokumentasi Pembelajaran (8).png"], cta: "Butuh Perawatan Kendaraan?", ctaCopy: "Temukan layanan otomotif bersama Garage26 melalui kompetensi dan pengalaman nyata siswa TKR." },
  gadizVokasi: { folder: "BLUD-GadizVokasi", name: "GADIZ VOKASI", code: "SIJA", color: "#ff7a00", hero: "Hero Section (8).png", visual: "image 3 (5).png", flow: "Alur BLUD (4).png", icon: "Button shortcut (4).png", whatsapp: "basil_whatsapp-solid (5).png", stats: [["130+", "Siswa Terlibat"], ["55+", "Client"], ["150+", "Project"], ["20+", "Jenis Produk"]], intro: "GADIZ VOKASI merupakan unit produksi dan layanan berbasis kompetensi Sistem Informasi, Jaringan dan Aplikasi yang menghadirkan berbagai kebutuhan percetakan melalui kreativitas dan keterampilan siswa.", description: "GADIZ VOKASI mengembangkan layanan desain, produksi, dan percetakan untuk menghasilkan produk yang sesuai kebutuhan dengan proses kerja yang terarah.", services: [["Tiket & Kartu", "Produksi berbagai kebutuhan tiket, kartu, dan media cetak."], ["Sablon", "Menerapkan desain visual ke berbagai media menggunakan teknik sablon."], ["Percetakan", "Menghasilkan berbagai kebutuhan cetak sesuai ukuran dan kebutuhan."], ["Desain Visual", "Menyiapkan materi visual untuk kebutuhan produk dan media cetak."]], projects: [["Custom Apparel Printing", "Custom Apparel Printing.png"], ["Sticker & Label Printing", "Sticker & Label Printing.png"], ["Custom Merchandise", "Custom Merchandise.png"], ["Digital Print & Branding", "Digital Print & Branding.png"]], docs: ["Dokumentasi Pembelajaran (13).png", "Dokumentasi Pembelajaran (14).png"], cta: "Punya Kebutuhan Percetakan?", ctaCopy: "Wujudkan kebutuhan cetak bersama GADIZ VOKASI melalui kreativitas dan keterampilan siswa SIJA." },
};

export function BludServicePage({ service }: { service: keyof typeof configs }) {
  const config = configs[service];
  const titleParts = config.name.split(" ");
  return <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]"><PublicNavbar /><main>
    <section className="relative isolate min-h-[620px] overflow-hidden bg-[#c5b7ba] pt-24 sm:min-h-[700px] lg:min-h-[760px] lg:pt-32"><img className="absolute inset-0 -z-10 size-full object-cover object-center" src={asset(config.folder, config.hero)} alt={`${config.name} SMKN 26 Jakarta`} /><div className="mx-auto flex w-full max-w-[1272px] px-5 pb-36 sm:px-8 lg:px-16 lg:pb-44"><div className="max-w-[590px] pt-10 text-white sm:pt-16 lg:pt-20"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase" style={{ color: config.color }}>BLUD • UNIT PRODUKSI &amp; LAYANAN</span><h1 className="mt-4 text-5xl font-bold leading-tight">{titleParts[0]} <span style={{ color: config.color }}>{titleParts.slice(1).join(" ")}</span></h1><p className="mt-4 max-w-[520px] text-sm leading-6 text-white/90 sm:text-base">{config.intro}</p></div></div></section>
    <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10" style={{ backgroundColor: config.color }}><div className="grid grid-cols-2 sm:grid-cols-4">{config.stats.map(([value, label]) => <div className="border-r border-dashed border-white/60 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
    <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset(config.folder, config.visual)} alt={`Siswa ${config.name}`} /><div><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase shadow-sm" style={{ color: config.color }}>TENTANG {config.name}</span><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Tentang <span style={{ color: config.color }}>{config.name}</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">{config.intro}</p><p className="mt-3 text-sm leading-6 text-[#61708b] sm:text-base">{config.description}</p></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase shadow-sm" style={{ color: config.color }}>LAYANAN &amp; PRODUK</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Layanan <span style={{ color: config.color }}>{config.name}</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Menghadirkan layanan berbasis kompetensi untuk menjawab kebutuhan di bidang {config.code}.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{config.services.map(([title, copy]) => <article className="flex gap-3 rounded-2xl bg-white p-5 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)]" key={title}><img className="size-9 shrink-0 rounded-full" src={asset(config.folder, config.icon)} alt="" aria-hidden="true" /><div><h3 className="text-lg font-bold" style={{ color: config.color }}>{title}</h3><p className="mt-1 text-xs leading-5 text-[#61708b]">{copy}</p></div></article>)}</div></div></section>
    <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase shadow-sm" style={{ color: config.color }}>ALUR LAYANAN</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Bagaimana <span style={{ color: config.color }}>{config.name}</span> Bekerja?</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Setiap layanan menerapkan kompetensi melalui proses kerja yang terarah dan nyata.</p><img className="mx-auto mt-8 hidden w-full object-contain md:block" src={asset(config.folder, config.flow)} alt={`Alur layanan ${config.name}`} /></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase shadow-sm" style={{ color: config.color }}>KARYA &amp; PORTOFOLIO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Karya Teknologi <span style={{ color: config.color }}>{config.name}</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Dari proses pembelajaran hingga menjadi karya yang dapat digunakan.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{config.projects.map(([title, photo]) => <article className="overflow-hidden rounded-2xl bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={title}><img className="aspect-square w-full object-cover" src={asset(config.folder, photo)} alt={title} /><div className="p-3"><h3 className="text-xs font-bold" style={{ color: config.color }}>{title}</h3><p className="mt-1 text-[10px] text-[#61708b]">{config.name} • {config.code}</p></div></article>)}</div></div></section>
    <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase shadow-sm" style={{ color: config.color }}>DI BALIK {config.name}</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Di Balik <span style={{ color: config.color }}>Setiap Karya</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Melihat proses siswa belajar, bekerja, dan berkarya.</p><div className="mx-auto mt-8 grid max-w-[1000px] gap-3">{config.docs.map((photo) => <img className="h-auto w-full rounded-2xl object-contain" src={asset(config.folder, photo)} alt={`Dokumentasi ${config.name}`} key={photo} />)}</div></div></section>
     <section className="px-6 py-14 text-center text-white sm:px-10 lg:py-16" style={{ backgroundColor: config.color }}><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase" style={{ color: config.color }}>KONTAK {config.name}</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">{config.cta}</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">{config.ctaCopy}</p><a className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-xs font-bold" style={{ color: config.color }} href="https://wa.me/6285212588797" target="_blank" rel="noreferrer"><img className="size-4 object-contain" src={asset(config.folder, config.whatsapp)} alt="" aria-hidden="true" />Hubungi {config.name}</a></section>
  </main><PublicFooter /></div>;
}
