import { PortalLayout } from '../layouts/PortalLayout';
import { RequireAuth } from '../features/auth/RequireAuth';
import { useEffect, useState } from 'react';
import { useAuth } from '../features/auth/AuthProvider';
import { Link } from '../routes/compat';
import { getLearningSummary } from '../features/learning/learning.api';
import type { LearningSummary } from '../features/learning/learning.types';
export function DashboardPage() { const { me, hasPermission } = useAuth(); const [learning, setLearning] = useState<LearningSummary | null>(null); useEffect(() => { if (me?.profile.account_type === 'STUDENT') getLearningSummary().then(setLearning).catch(() => setLearning(null)); }, [me?.profile.account_type]); return <RequireAuth><PortalLayout><div className="portal-intro"><div><p className="text-sm font-semibold text-primary">Ruang kerja internal</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Selamat datang, {me?.profile.display_name}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted">Akses pembelajaran dan tugas sekolah yang ditugaskan untuk akun Anda.</p></div><div className="hidden rounded-2xl bg-white/80 p-4 sm:block"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted">Akun aktif</p><p className="mt-2 text-lg font-bold text-primary-dark">{me?.profile.account_type}</p></div></div>{me?.profile.account_type === 'STUDENT' && learning && <div className="mt-8 grid gap-3 sm:grid-cols-3"><DashboardMetric label="Mata pelajaran dinilai" value={learning.summary.assessedSubjects} /><DashboardMetric label="Topik perlu perhatian" value={learning.summary.needsAttention} tone="warm" /><DashboardMetric label="Topik sesuai target" value={learning.summary.mastered} /></div>}<div className="mt-8 grid gap-5 md:grid-cols-2">{me?.profile.account_type === 'STUDENT' && <PortalCard to="/dashboard/learning" eyebrow="Belajar lebih terarah" title="Rekomendasi Belajar" copy="Lihat perkembangan topik dan sumber belajar yang disetujui." accent="blue" />}{hasPermission('grades:manage') && <PortalCard to="/dashboard/grades" eyebrow="Kompetensi siswa" title="Input Nilai" copy="Kelola assessment hanya pada kelas dan mata pelajaran yang ditugaskan." accent="yellow" />}{hasPermission('content:manage') && <PortalCard to="/admin/knowledge" eyebrow="Konten publik" title="Knowledge Base" copy="Tinjau sumber informasi sebelum digunakan chatbot publik." accent="blue" />}</div><div className="mt-8 rounded-[24px] border border-light-blue bg-white p-5 sm:p-6"><p className="text-sm font-semibold text-primary">Profil portal</p><div className="mt-4 flex flex-wrap gap-x-8 gap-y-2 text-sm text-muted"><span><strong className="text-ink">Identifier</strong> {me?.profile.school_identifier}</span><span><strong className="text-ink">Status</strong> Aktif</span></div></div></PortalLayout></RequireAuth>; }
function DashboardMetric({ label, value, tone = 'blue' }: { label: string; value: number; tone?: 'blue' | 'warm' }) { return <div className={`rounded-2xl border p-5 ${tone === 'warm' ? 'border-accent/30 bg-[#fffaf0]' : 'border-light-blue bg-white'}`}><p className={`text-3xl font-bold ${tone === 'warm' ? 'text-[#b87800]' : 'text-primary-dark'}`}>{value}</p><p className="mt-2 text-sm leading-5 text-muted">{label}</p></div>; }
function PortalCard({ to, eyebrow, title, copy, accent }: { to: string; eyebrow: string; title: string; copy: string; accent: 'blue' | 'yellow' }) { return <Link to={to} className="group relative overflow-hidden rounded-[24px] border border-light-blue bg-white p-6 shadow-[0_8px_24px_rgba(15,23,42,.05)] transition hover:-translate-y-1 hover:shadow-[0_14px_30px_rgba(15,23,42,.1)]"><span className={`absolute right-5 top-5 size-12 rounded-full ${accent === 'yellow' ? 'bg-accent/20' : 'bg-light-blue'}`} /><p className="relative text-sm font-semibold text-primary">{eyebrow}</p><h2 className="relative mt-8 text-2xl font-bold text-ink">{title}</h2><p className="relative mt-2 max-w-sm text-sm leading-6 text-muted">{copy}</p><span className="relative mt-6 inline-flex text-sm font-bold text-primary">Buka modul <span className="ml-2 transition group-hover:translate-x-1">→</span></span></Link>; }
