import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";

const asset = (name: string) => `/assets/figma/BLUD-E-MAN/${name}`;

const services = [
  ["Instalasi Listrik", "Pemasangan dan penataan instalasi kelistrikan sesuai kebutuhan."],
  ["Perawatan & Perbaikan", "Pemeriksaan dan penanganan masalah pada instalasi listrik."],
  ["Sistem Penerangan", "Pemasangan dan pengembangan sistem pencahayaan untuk berbagai kebutuhan."],
  ["Pemeriksaan Killstreak", "Pengecekan kondisi instalasi untuk membantu memastikan keamanan dan fungsinya."],
] as const;

const projects = [
  ["Instalasi Panel Listrik Gedung", "Instalasi Panel Listrik Gedung.png"],
  ["Sistem Penerangan Otomatis", "Sistem Penerangan Otomatis.png"],
  ["Trainer Instalasi Listrik Rumah", "Trainer Instalasi Listrik Rumah.png"],
  ["Panel Kontrol Motor Listrik", "Panel Kontrol Motor Listrik.png"],
] as const;

export function EmanPage() {
  return (
    <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]
      "><PublicNavbar /><main>
      <section className="relative isolate min-h-[620px] overflow-hidden bg-[#bdb7a2] pt-24 sm:min-h-[700px] lg:min-h-[760px] lg:pt-32"><img className="absolute inset-0 -z-10 size-full object-cover object-center" src={asset("Hero Section (6).png")} alt="E-MAN SMKN 26 Jakarta" /><div className="mx-auto flex w-full max-w-[1272px] px-5 pb-36 sm:px-8 lg:px-16 lg:pb-44"><div className="max-w-[560px] pt-10 text-white sm:pt-16 lg:pt-20"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900]">BLUD • UNIT PRODUKSI &amp; LAYANAN</span><h1 className="mt-4 text-5xl font-bold leading-tight">E-<span className="text-[#ffc533]">MAN</span></h1><p className="mt-4 max-w-[480px] text-sm leading-6 text-white/90 sm:text-base">E-MAN merupakan unit produksi dan layanan berbasis kompetensi Teknik Instalasi Tenaga Listrik, yang dikelola oleh siswa untuk menerapkan keterampilan kelistrikan melalui pengalaman dan pekerjaan nyata.</p></div></div></section>
      <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#ffc533] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["180+", "Siswa Terlibat"], ["30+", "Client"], ["65+", "Project"], ["12+", "Jenis Layanan"]].map(([value, label]) => <div className="border-r border-dashed border-white/60 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
      <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 4 (1).png")} alt="Siswa E-MAN mengerjakan proyek kelistrikan" /><div><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900] shadow-sm">TENTANG E-MAN</span><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Tentang <span className="text-[#e5a900]">E-MAN</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">E-MAN adalah unit produksi dan layanan yang menjadi ruang bagi siswa Teknik Instalasi Tenaga Listrik untuk menerapkan kompetensi kelistrikan melalui pekerjaan dan proyek nyata.</p><p className="mt-3 text-sm leading-6 text-[#61708b] sm:text-base">E-MAN, siswa tidak hanya mempelajari instalasi listrik, tetapi juga belajar merancang, memasang, menguji, dan memastikan pekerjaan dilakukan sesuai prosedur keselamatan kerja.</p></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900] shadow-sm">LAYANAN &amp; PRODUK</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Layanan <span className="text-[#e5a900]">E-MAN</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Mengaplikasikan kompetensi TITL untuk menghadirkan solusi kelistrikan yang tepat, aman, dan sesuai kebutuhan.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{services.map(([title, copy]) => <article className="flex gap-3 rounded-2xl bg-white p-5 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)]" key={title}><img className="size-9 shrink-0 rounded-full" src={asset("Button shortcut (5).png")} alt="" aria-hidden="true" /><div><h3 className="text-lg font-bold text-[#e5a900]">{title}</h3><p className="mt-1 text-xs leading-5 text-[#61708b]">{copy}</p></div></article>)}</div></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900] shadow-sm">ALUR LAYANAN</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Bagaimana <span className="text-[#e5a900]">E-MAN</span> Bekerja?</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">E-MAN menghadirkan solusi kelistrikan melalui proses kerja yang terarah dan aman.</p><img className="mx-auto mt-8 hidden w-full object-contain md:block" src={asset("Alur BLUD (2).png")} alt="Alur layanan E-MAN" /><div className="mt-8 grid gap-4 text-left md:hidden">{["Konsultasi", "Pemeriksaan", "Pengerjaan", "Pengujian", "Penyelesaian"].map((step, index) => <div className="rounded-2xl bg-white p-4" key={step}><strong className="text-[#e5a900]">0{index + 1} — {step}</strong></div>)}</div></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900] shadow-sm">KARYA &amp; PORTOFOLIO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Karya Teknologi <span className="text-[#e5a900]">E-MAN</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Dari perencanaan, pengerjaan, hingga menjadi solusi kelistrikan yang dapat digunakan.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{projects.map(([title, photo]) => <article className="overflow-hidden rounded-2xl bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={title}><img className="aspect-square w-full object-cover" src={asset(photo)} alt={title} /><div className="p-3"><h3 className="text-xs font-bold text-[#e5a900]">{title}</h3><p className="mt-1 text-[10px] text-[#61708b]">E-MAN • TITL</p></div></article>)}</div></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900] shadow-sm">DI BALIK E-MAN</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Di Balik <span className="text-[#e5a900]">Setiap Karya</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Melihat proses siswa TITL belajar, bekerja, dan menerapkan keterampilan kelistrikan.</p><div className="mx-auto mt-8 grid max-w-[1000px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (3).png")} alt="Kegiatan E-MAN baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (4).png")} alt="Kegiatan E-MAN baris kedua" /></div></div></section>
      <section className="bg-[#ffc533] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e5a900]">KONTAK E-MAN</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Punya Kebutuhan Kelistrikan?</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Temukan solusi kelistrikan bersama E-MAN melalui kompetensi dan pengalaman nyata siswa TITL.</p><a className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-xs font-bold text-[#e5a900]" href="/information"><img className="size-4 object-contain" src={asset("basil_whatsapp-solid (2).png")} alt="" aria-hidden="true" />Hubungi E-MAN</a></section>
    </main><PublicFooter /></div>
  );
}
