import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";

const asset = (name: string) => `/assets/figma/BLUD-KGS/${name}`;

const services = [
  ["Perencanaan", "Mendukung proses perencanaan kebutuhan konstruksi secara terarah."],
  ["Pengukuran", "Melakukan pengukuran dan perhitungan sesuai kebutuhan pekerjaan."],
  ["Pekerjaan Konstruksi", "Menerapkan kompetensi konstruksi melalui proses pengerjaan secara nyata."],
  ["Sanitasi", "Mendukung kebutuhan pekerjaan yang berkaitan dengan sistem sanitasi."],
] as const;

const projects = [
  ["Proyek Konstruksi Bangunan", "Proyek Konstruksi Bangunan.png"],
  ["Proyek Pekerjaan Struktur", "Proyek Pekerjaan Struktur.png"],
  ["Proyek Gambar Teknik", "Proyek Gambar Teknik.png"],
  ["Proyek Pemasangan Keramik", "Proyek Pemasangan Keramik.png"],
] as const;

const steps = [
  ["01", "Perencanaan", "Memahami kebutuhan dan tujuan pekerjaan."],
  ["02", "Perencanaan", "Menentukan rancangan dan kebutuhan pekerjaan."],
  ["03", "Pengerjaan", "Menerapkan kompetensi melalui proses kerja nyata."],
  ["04", "Penyelesaian", "Melakukan pemeriksaan dan menyelesaikan hasil pekerjaan."],
] as const;

export function KgStudioPage() {
  return (
    <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]
      "><PublicNavbar /><main>
      <section className="relative isolate min-h-[620px] overflow-hidden bg-[#d5c8cc] pt-24 sm:min-h-[700px] lg:min-h-[760px] lg:pt-32"><img className="absolute inset-0 -z-10 size-full object-cover object-center" src={asset("Hero Section (4).png")} alt="KGStudio SMKN 26 Jakarta" /><div className="mx-auto flex w-full max-w-[1272px] px-5 pb-36 sm:px-8 lg:px-16 lg:pb-44"><div className="max-w-[560px] pt-10 text-white sm:pt-16 lg:pt-20"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613]">BLUD • UNIT PRODUKSI &amp; LAYANAN</span><h1 className="mt-4 text-5xl font-bold leading-tight lg:text-[64px]">KG<span className="text-[#e30613]">Studio</span></h1><p className="mt-4 max-w-[480px] text-sm leading-6 text-white/90 sm:text-base">KGStudio menghadirkan layanan berbasis kompetensi vokasi Konstruksi Gedung dan Sanitasi, dari proses perencanaan hingga menghasilkan karya yang nyata.</p></div></div></section>
      <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#ed1c24] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["120+", "Siswa Terlibat"], ["35+", "Client"], ["80+", "Project"], ["15+", "Jenis Layanan"]].map(([value, label]) => <div className="border-r border-dashed border-white/60 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
      <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 3 (4).png")} alt="Siswa KGStudio mengerjakan proyek konstruksi" /><div><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613] shadow-sm">TENTANG KGSTUDIO</span><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Tentang <span className="text-[#e30613]">KGStudio</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">KGStudio merupakan unit produksi dan layanan berbasis kompetensi vokasi di bidang Konstruksi Gedung dan Sanitasi. Melalui KGStudio, pembelajaran tidak hanya berlangsung di dalam kelas, tetapi diterapkan melalui pengalaman dan pengerjaan nyata.</p><p className="mt-3 text-sm leading-6 text-[#61708b] sm:text-base">Dengan menggabungkan keterampilan, kreativitas, dan penerapan teknologi, KGStudio menjadi ruang bagi siswa untuk mengembangkan kompetensi sekaligus menghasilkan karya yang memiliki nilai guna.</p></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613] shadow-sm">LAYANAN &amp; PRODUK</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Layanan <span className="text-[#e30613]">KGStudio</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Menghadirkan layanan berbasis kompetensi untuk menjawab kebutuhan di bidang konstruksi dan sanitasi.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{services.map(([title, copy]) => <article className="flex gap-3 rounded-2xl bg-white p-5 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)]" key={title}><img className="size-9 shrink-0 rounded-full" src={asset("Button shortcut (4).png")} alt="" aria-hidden="true" /><div><h3 className="text-lg font-bold text-[#e30613]">{title}</h3><p className="mt-1 text-xs leading-5 text-[#61708b]">{copy}</p></div></article>)}</div></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613] shadow-sm">ALUR LAYANAN</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Bagaimana <span className="text-[#e30613]">KGStudio</span> Bekerja?</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Setiap layanan KGStudio menerapkan kompetensi konstruksi melalui proses kerja yang nyata.</p><img className="mx-auto mt-8 hidden w-full object-contain md:block" src={asset("Alur BLUD.png")} alt="Alur layanan KGStudio" /><div className="mt-8 grid gap-4 text-left md:hidden">{steps.map(([number, title, copy]) => <div className="rounded-2xl bg-white p-4" key={number}><strong className="text-[#e30613]">{number} — {title}</strong><p className="mt-1 text-xs text-[#61708b]">{copy}</p></div>)}</div></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613] shadow-sm">KARYA &amp; PORTOFOLIO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Karya Nyata <span className="text-[#e30613]">KGStudio</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Dari pembelajaran menjadi karya yang dapat dilihat dan dirasakan.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{projects.map(([title, photo]) => <article className="overflow-hidden rounded-2xl bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={title}><img className="aspect-square w-full object-cover" src={asset(photo)} alt={title} /><div className="p-3"><h3 className="text-xs font-bold text-[#e30613]">{title}</h3><p className="mt-1 text-[10px] text-[#61708b]">KGStudio • KGS</p></div></article>)}</div></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613] shadow-sm">DI BALIK KGSTUDIO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Di Balik <span className="text-[#e30613]">Setiap Karya</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Melihat proses belajar, bekerja, dan berkarya bersama KGStudio.</p><div className="mx-auto mt-8 grid max-w-[1000px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (9).png")} alt="Kegiatan KGStudio baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (10).png")} alt="Kegiatan KGStudio baris kedua" /></div></div></section>
      <section className="bg-[#ed1c24] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#e30613]">KONTAK KGSTUDIO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Punya Kebutuhan di Bidang Konstruksi?</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Temukan layanan KGStudio dan kenali bagaimana kompetensi vokasi diterapkan menjadi karya nyata.</p><a className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-xs font-bold text-[#e30613]" href="/information"><img className="size-4 object-contain" src={asset("basil_whatsapp-solid.png")} alt="" aria-hidden="true" />Hubungi KGStudio</a></section>
    </main><PublicFooter /></div>
  );
}
