import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";
import { CtaLink } from "../components/public/CtaLink";

const asset = (name: string) => `/assets/figma/Organisasi/${name}`;
const gallery = Array.from({ length: 8 }, (_, index) => `Foto kegiatan (${index + 1}).png`);
const mission = [
  "Mendorong siswa untuk aktif dalam kegiatan sekolah.",
  "Mengembangkan jiwa kepemimpinan dan tanggung jawab.",
  "Menjadi ruang bagi siswa untuk menyampaikan aspirasi.",
  "Membangun kerja sama dan solidaritas antarsiswa.",
  "Mendukung kegiatan sekolah yang positif dan edukatif.",
];

function Label({ children }: { children: string }) {
  return <span className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-1.5 text-[10px] font-medium uppercase tracking-wide text-[#39aef2] shadow-[0_4px_12px_rgba(15,23,42,.08)]"><span className="size-1.5 rounded-full bg-[#39aef2]" />{children}</span>;
}

export function OrganisasiSekolahPage() {
  return <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]"><PublicNavbar /><main>
    <section className="relative isolate z-20 min-h-[865px] overflow-visible bg-[#eaf5ff] px-6 pt-[140px] md:min-h-[895px] md:px-10"><img className="pointer-events-none absolute inset-0 z-0 size-full object-cover object-top" src={asset("hero.png")} alt="Kegiatan organisasi OSIS dan MPK SMKN 26 Jakarta" /><div className="pointer-events-none absolute inset-0 z-[1] bg-gradient-to-b from-[#eaf5ff]/0 via-[#eaf5ff]/0 to-[#eaf5ff]/10" /><div className="relative z-10 mx-auto flex max-w-[1100px] flex-col items-center text-center"><Label>ORGANISASI SMK NEGERI 26 JAKARTA</Label><h1 className="mt-4 max-w-[1000px] text-[32px] font-bold leading-10 tracking-[-.02em] text-white drop-shadow-[0_3px_3px_rgba(15,23,42,.14)] md:text-[48px] md:leading-[58px]">Wadah Siswa untuk <span className="bg-[linear-gradient(90deg,#4cbaf5,#0092ff_50%,#006cdc)] bg-clip-text text-transparent">Berkarya dan Berkontribusi</span></h1><p className="mt-3 max-w-[900px] text-base font-medium leading-6 text-white drop-shadow-[0_2px_3px_rgba(15,23,42,.2)] md:text-[20px] md:leading-[30px]">OSIS dan MPK SMKN 26 Jakarta menjadi bagian dari kehidupan sekolah yang mendorong siswa untuk belajar berorganisasi, menyampaikan aspirasi, bekerja sama, dan mengambil peran dalam berbagai kegiatan sekolah.</p><CtaLink className="mt-4" href="#organisasi">Kenali Organisasi</CtaLink></div></section>
    <section className="relative z-20 mx-auto -mt-8 grid w-[calc(100%-32px)] max-w-[1000px] grid-cols-3 overflow-hidden rounded-lg bg-gradient-to-r from-[#48b9f0] via-[#0092ff] to-[#006cdc] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10">{[["20+", "Ekstrakurikuler"], ["6", "Bidang Keahlian"], ["1", "Komunitas Sekolah"]].map(([value, label]) => <div className="border-r border-dashed border-white/70 px-2 py-3 last:border-r-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</section>
    <section id="organisasi" className="bg-white px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto grid max-w-[1100px] items-center gap-8 md:grid-cols-[.9fr_1.1fr]"><img className="mx-auto w-full max-w-[498px] object-contain" src={asset("Ekstrakurikuler (1).png")} alt="Siswa OSIS dan MPK SMKN 26 Jakarta" /><div><h2 className="text-3xl font-bold leading-tight sm:text-4xl">Berorganisasi, Berkarya, dan <span className="text-primary">Berkontribusi</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">OSIS dan MPK hadir sebagai wadah bagi siswa untuk mengembangkan kemampuan kepemimpinan, komunikasi, tanggung jawab, dan kerja sama melalui berbagai kegiatan di lingkungan sekolah.</p><h3 className="mt-4 text-sm font-bold text-primary">OSIS — Organisasi Siswa Intra Sekolah</h3><p className="text-sm leading-6 text-[#61708b]">Wadah bagi siswa untuk merancang dan menjalankan berbagai kegiatan serta program kesiswaan di sekolah.</p><h3 className="mt-2 text-sm font-bold text-primary">MPK — Majelis Perwakilan Kelas</h3><p className="text-sm leading-6 text-[#61708b]">Menjadi wadah perwakilan siswa untuk menyampaikan aspirasi dan ikut berperan dalam kehidupan organisasi sekolah.</p></div></div></section>
    <section className="bg-[#edf4ff] px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><h2 className="text-2xl font-bold sm:text-3xl"><span className="text-primary">Visi</span> &amp; <span className="text-primary">Misi</span> Organisasi</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Menjadi ruang bagi siswa untuk belajar memimpin, berkolaborasi, dan berkontribusi dalam kehidupan sekolah.</p><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="group relative min-h-[230px] overflow-hidden rounded-[24px] bg-white p-6 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)] transition-[box-shadow,transform] duration-300 hover:-translate-y-1 hover:shadow-[0_12px_28px_rgba(15,23,42,.1)]"><div className="relative z-10 max-w-[calc(100%-120px)]"><Label>VISI ORGANISASI</Label><p className="mt-4 text-sm font-bold leading-6">Mewujudkan organisasi siswa yang aktif, bertanggung jawab, kolaboratif, dan mampu memberikan kontribusi positif bagi lingkungan sekolah.</p><span className="mt-5 block h-1 w-9 bg-primary" /></div><img className="pointer-events-none absolute inset-y-0 right-0 z-0 h-full w-[134px] translate-x-full object-cover opacity-0 transition-[transform,opacity] duration-300 group-hover:translate-x-0 group-hover:opacity-100" src="/assets/figma/lsp/Shape%20(1).png" alt="" aria-hidden="true" /></article><article className="group relative min-h-[230px] overflow-hidden rounded-[24px] bg-white p-6 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)] transition-[box-shadow,transform] duration-300 hover:-translate-y-1 hover:shadow-[0_12px_28px_rgba(15,23,42,.1)]"><div className="relative z-10 max-w-[calc(100%-90px)]"><Label>MISI ORGANISASI</Label><ol className="mt-4 list-decimal space-y-1 pl-5 text-xs font-bold leading-4">{mission.map((item) => <li key={item}>{item}</li>)}</ol><span className="mt-5 block h-1 w-9 bg-primary" /></div><img className="pointer-events-none absolute inset-y-0 right-0 z-0 h-full w-[134px] translate-x-full object-cover opacity-0 transition-[transform,opacity] duration-300 group-hover:translate-x-0 group-hover:opacity-100" src="/assets/figma/lsp/Shape%20(1).png" alt="" aria-hidden="true" /></article></div></div></section>
    <section className="bg-[#edf4ff] px-6 pb-14 sm:px-10 lg:pb-20"><div className="mx-auto max-w-[1140px] text-center"><Label>STRUKTUR ORGANISASI</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Struktur Organisasi <span className="text-primary">OSIS &amp; MPK</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Kenali susunan kepengurusan serta peran OSIS dan MPK dalam menjalankan organisasi dan mewadahi aspirasi siswa.</p><div className="mt-8 grid gap-5 md:grid-cols-2"><a href="/programs/organisasi/osis" className="rounded-2xl bg-white p-6 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)] transition-[box-shadow,transform] duration-300 hover:-translate-y-1 hover:shadow-[0_12px_28px_rgba(15,23,42,.12)] motion-reduce:transition-none"><img alt="" aria-hidden="true" className="size-12" src={asset("Button shortcut (12).png")} /><h3 className="mt-3 text-lg font-bold text-primary">Struktur Organisasi OSIS</h3><p className="mt-2 text-xs font-normal leading-5 text-[#61708b]">Mengenal susunan kepengurusan OSIS<br />serta peran setiap anggota dalam<br />menjalankan berbagai kegiatan dan program sekolah.</p></a><a href="/programs/organisasi/mpk" className="rounded-2xl bg-white p-6 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)] transition-[box-shadow,transform] duration-300 hover:-translate-y-1 hover:shadow-[0_12px_28px_rgba(15,23,42,.12)] motion-reduce:transition-none"><img alt="" aria-hidden="true" className="size-12" src={asset("Button shortcut (12).png")} /><h3 className="mt-3 text-lg font-bold text-primary">Struktur Organisasi MPK</h3><p className="mt-2 text-xs font-normal leading-5 text-[#61708b]">Mengenal susunan kepengurusan MPK<br />serta perannya sebagai wadah<br />perwakilan dan penyampaian aspirasi siswa.</p></a></div></div></section>
    <section className="bg-[#edf4ff] px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>GALERI KEGIATAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Bergerak Bersama <span className="text-primary">Menciptakan Cerita</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Dokumentasikan berbagai kegiatan OSIS dan MPK sebagai bagian dari perjalanan siswa dalam belajar berorganisasi, bekerja sama, dan memberikan kontribusi bagi sekolah.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{gallery.map((photo) => <img className="aspect-square w-full rounded-2xl object-cover" src={asset(photo)} alt="Kegiatan OSIS dan MPK" key={photo} />)}</div></div></section>
  </main><PublicFooter /></div>;
}
