import { useRef } from "react";

import { figmaAssets } from "../assets/figmaAssets";
import { IndustryPartnersMarquee } from "../components/public/IndustryPartnersMarquee";
import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";

const asset = (name: string) => `/assets/figma/SIJA/${name}`;
const competencies = ["Pemrograman", "Pengembangan Aplikasi", "Jaringan Komputer", "Sistem Informasi", "Basis Data", "Cloud & Infrastruktur", "Keamanan Sistem", "UI/UX Design"];
const achievements = [["Muhammad Fauzan", "Juara 2 - Network & IT Competition", "Muhammad Fauzan.png"], ["Angelica Putri", "Juara 1 - Kompetisi Aplikasi Pelajar", "Angelica Putri.png"], ["Nabilla Mallya", "Finalis - Digital Innovation Competition", "Nabilla Mallya.png"], ["Bagus Rahmansyah", "Juara 3 - Web Development Competition", "Bagus Rahmansyah.png"]] as const;
const alumni = [["Raka Aditya", "Raka Pratama.png", "SIJA — Angkatan 50", "Software Developer", "Selama belajar di SIJA, saya terbiasa membuat proyek dan menyelesaikan masalah secara langsung. Pengalaman tersebut menjadi bekal penting ketika mulai bekerja di bidang teknologi."], ["Marwan", "Marwan.png", "SIJA — Angkatan 49", "Network Engineer", "Praktik jaringan dan proyek selama di SIJA membuat saya lebih memahami bagaimana teknologi digunakan di dunia kerja. Saya jadi lebih percaya diri untuk mengembangkan karier di bidang IT."]] as const;

function Label({ children }: { children: string }) { return <span className="inline-flex items-center gap-1 rounded-full bg-[#f6fbff] px-3 py-[5px] text-sm font-medium text-[#FF7700] shadow-[0_4px_16px_rgba(15,23,42,.08)]"><span className="h-[17px] w-[13.6px] bg-current [mask:url('/assets/figma/majors/icon-section-badge.svg')_center/contain_no-repeat]" aria-hidden="true" />{children}</span>; }

export function SijaPage() {
  const alumniTrackRef = useRef<HTMLDivElement>(null);
  function scrollAlumni(direction: number) { alumniTrackRef.current?.scrollBy({ left: direction * (alumniTrackRef.current?.clientWidth ?? 0) * 0.6, behavior: "smooth" }); }

  return <div className="min-h-screen overflow-x-clip bg-white text-[#10182b]"><PublicNavbar /><main className="[&>section:nth-of-type(3)]:bg-white [&>section:nth-of-type(3)]:shadow-[0_0_0_100vmax_#fff]">
    <section className="relative isolate w-full overflow-hidden bg-[#c7b8ac]"><div className="relative mx-auto aspect-[1440/650] min-h-[540px] w-full sm:min-h-[580px] lg:min-h-0"><img className="absolute inset-0 z-0 size-full object-cover object-[68%_center] sm:object-[78%_center] lg:object-center" src={asset("Hero Section (5).png")} alt="Siswa Sistem Informasi, Jaringan dan Aplikasi" /><div className="relative z-10 mx-auto flex h-full w-[calc(100%-32px)] max-w-[1272px] items-start pl-5 pr-4 pt-[132px] sm:pl-7 sm:pr-6 sm:pt-[176px] lg:pt-[192px]"><div className="max-w-[700px] text-white"><Label>JURUSAN SIJA</Label><h1 className="mt-4 text-[34px] font-bold leading-[1.08] sm:text-5xl lg:text-[56px] xl:text-[60px]">Sistem Informasi, <span className="text-[#FF9E49]">Jaringan &amp; Aplikasi</span></h1><p className="mt-4 max-w-[700px] text-sm leading-5 text-white/90 sm:text-base sm:leading-6">Membekali siswa dengan keterampilan teknologi informasi melalui pengembangan aplikasi, pengelolaan jaringan, sistem informasi, dan solusi digital yang dekat dengan kebutuhan industri.</p></div></div></div></section>
    <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#FF7700] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["4 Tahun", "Program Pendidikan"], ["30+", "Mitra Industri"], ["288+", "Siswa"], ["50+", "Prestasi SIJA"]].map(([value, label]) => <div className="border-r border-white/40 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
    <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 3 (4).png")} alt="Siswa Sistem Informasi, Jaringan dan Aplikasi" /><div><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Mengenal<br /><span className="text-[#FF7700]">Sistem Informasi, Jaringan &amp; Aplikasi</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">SIJA membekali siswa dengan keterampilan mengembangkan aplikasi, mengelola jaringan, dan membangun sistem informasi melalui pembelajaran teori dan praktik dengan mengutamakan ketelitian, kreativitas, dan pemecahan masalah.</p><p className="mt-3 text-sm font-bold text-[#FF7700]">Membangun solusi digital dari ide menjadi nyata.</p></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>KOMPETENSI UTAMA</Label><h2 className="mt-4 text-[26px] font-bold sm:text-[34px]">Kompetensi <span className="text-[#FF7700]">yang Dipelajari</span></h2><p className="mx-auto mt-3 max-w-[760px] text-sm leading-6 text-[#61708b] sm:text-base sm:leading-7">Siswa SIJA mengembangkan keterampilan pemrograman, jaringan, basis data, sistem informasi, dan pengembangan aplikasi melalui teori serta proyek.</p><div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-4">{competencies.map((item) => <div className="flex items-center gap-3 rounded-2xl bg-white px-4 py-4 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)] sm:px-5" key={item}><img className="size-10 shrink-0 rounded-full sm:size-11" src={asset("Button shortcut (4).png")} alt="" aria-hidden="true" /><span className="text-sm font-medium leading-tight sm:text-base">{item}</span></div>)}</div></div></section>
    <section className="px-5 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>ROADMAP PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari Dasar hingga Siap Berkarya <span className="text-[#FF7700]">#Program4Tahun</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Empat tahun perjalanan untuk mengenal, mengembangkan, menerapkan, dan menguji kompetensi teknologi informasi di dunia industri.</p><img className="mx-auto mt-8 w-full max-w-[1140px] object-contain" src={asset("Roadmap Jurusan.png")} alt="Roadmap pembelajaran SIJA" /></div></section>
    <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1200px] text-center"><Label>KEGIATAN PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Belajar Tidak Hanya di <span className="text-[#FF7700]">Dalam Kelas</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Pengalaman belajar SIJA hadir melalui perpaduan teori, praktik, proyek, dan kegiatan yang membantu siswa memahami teknologi digital secara langsung.</p><div className="mx-auto mt-8 grid max-w-[1100px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (9).png")} alt="Dokumentasi pembelajaran SIJA baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (10).png")} alt="Dokumentasi pembelajaran SIJA baris kedua" /></div></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>CIRI KHAS SIJA</Label></div><div className="mx-auto mt-8 grid max-w-[1140px] items-center gap-8 sm:gap-12 lg:grid-cols-2"><div className="text-left"><h2 className="text-[26px] font-bold leading-[1.15] sm:text-[34px]">Identitas <span className="text-[#FF7700]">Sistem Informasi, Jaringan &amp; Aplikasi #Wearpack</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base sm:leading-7">Wearpack menjadi salah satu identitas siswa SIJA yang mencerminkan kedekatan dengan lingkungan kerja teknologi. Dalam setiap praktik, siswa dibiasakan menggunakan perangkat dan tools secara tepat, memahami proses kerja, memecahkan masalah, serta mengembangkan solusi digital sesuai kebutuhan.</p></div><img className="mx-auto w-full max-w-[460px] object-contain" src={asset("image 3 (4).png")} alt="Identitas siswa SIJA dengan wearpack" /></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1200px] text-center"><Label>PRESTASI SISWA</Label><h2 className="mt-4 text-[26px] font-bold sm:text-[34px]">Prestasi yang Dibangun <span className="text-[#FF7700]">dari Kompetensi</span></h2><p className="mx-auto mt-3 max-w-[760px] text-sm leading-6 text-[#61708b] sm:text-base sm:leading-7">Kompetensi yang dipelajari menjadi bekal siswa SIJA untuk berkompetisi, berinovasi, dan menunjukkan kemampuan di bidang teknologi informasi.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{achievements.map(([name, achievement, photo]) => <article className="overflow-hidden rounded-[20px] bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={name}><img className="w-full object-cover" src={asset(photo)} alt={name} /><div className="p-4"><h3 className="text-base font-bold text-[#FF7700]">{name}</h3><span className="mt-1 block h-[3px] w-[48px] rounded-full bg-[#FF7700]" aria-hidden="true" /><p className="mt-2 text-sm leading-5 text-[#10182b]">{achievement}</p></div></article>)}</div></div></section>
    <IndustryPartnersMarquee accent="text-[#FF7700]" barClass="bg-[#FF7700]" labelClass="bg-[#fff0e4] text-[#FF7700]" stats={[["8+", "Mitra Industri"], ["12+", "Program Kolaborasi"], ["20+", "Kegiatan Industri"]]} />
    <section className="bg-[linear-gradient(90deg,#ff9e49,#FF7700_50%,#c65300)] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><Label>ALUMNI SIJA</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari SIJA, Melangkah Lebih Jauh</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Kompetensi yang diperoleh selama belajar menjadi bekal alumni untuk memasuki dunia industri teknologi, melanjutkan pendidikan, maupun mengembangkan karier di bidang digital.</p><div className="mx-auto mt-8 flex max-w-[1200px] items-center gap-3 sm:gap-5"><button type="button" onClick={() => scrollAlumni(-1)} aria-label="Alumni sebelumnya" className="group hidden size-11 shrink-0 cursor-pointer place-items-center rounded-full bg-white shadow-[0_4px_15px_rgba(0,0,0,.2)] transition hover:bg-[#FF7700] md:grid"><img className="size-5 transition-[filter] group-hover:brightness-0 group-hover:invert" src={figmaAssets.advantages.arrowLeft} alt="" /></button><div ref={alumniTrackRef} className="flex min-w-0 flex-1 gap-5 overflow-x-auto pb-1 [scrollbar-width:none] [touch-action:pan-y] [&::-webkit-scrollbar]:hidden">{alumni.map(([name, photo, batch, work, quote]) => <article className="flex w-[85%] shrink-0 items-start gap-4 rounded-2xl bg-white p-4 text-left text-[#10182b] sm:gap-5 sm:p-5 md:w-[calc(50%-10px)]" key={name}><img className="size-28 shrink-0 rounded-xl object-cover sm:size-36" src={asset(photo)} alt={name} /><div className="min-w-0"><strong className="block text-base sm:text-lg">{name}</strong><span className="mt-1 block text-xs text-[#61708b] sm:text-sm">{batch}</span><strong className="mt-2 block text-xs text-[#FF7700] sm:text-sm">{work}</strong><p className="mt-2 text-xs leading-5 text-[#61708b] sm:text-sm">“{quote}”</p></div></article>)}</div><button type="button" onClick={() => scrollAlumni(1)} aria-label="Alumni berikutnya" className="group hidden size-11 shrink-0 cursor-pointer place-items-center rounded-full bg-white shadow-[0_4px_15px_rgba(0,0,0,.2)] transition hover:bg-[#FF7700] md:grid"><img className="size-5 transition-[filter] group-hover:brightness-0 group-hover:invert" src={figmaAssets.advantages.arrowRight} alt="" /></button></div></section>
  </main><PublicFooter /></div>;
}
