import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";
import { IndustryPartnersMarquee } from "../components/public/IndustryPartnersMarquee";

const asset = (name: string) => `/assets/figma/SIJA/${name}`;
const competencies = ["Pemrograman", "Pengembangan Aplikasi", "Jaringan Komputer", "Sistem Informasi", "Basis Data", "Cloud & Infrastruktur", "Keamanan Sistem", "UI/UX Design"];
const achievements = [["Muhammad Fauzan", "Juara 2 - Network & IT Competition", "Muhammad Fauzan.png"], ["Angelica Putri", "Juara 1 - Kompetisi Aplikasi Pelajar", "Angelica Putri.png"], ["Nabilla Mallya", "Finalis - Digital Innovation Competition", "Nabilla Mallya.png"], ["Bagus Rahmansyah", "Juara 3 - Web Development Competition", "Bagus Rahmansyah.png"]] as const;
const alumni = [["Raka Aditya", "Raka Pratama.png", "SIJA — Angkatan 50", "Software Developer", "Selama belajar di SIJA, saya terbiasa membuat proyek dan menyelesaikan masalah secara langsung. Pengalaman tersebut menjadi bekal penting ketika mulai bekerja di bidang teknologi."], ["Marwan", "Marwan.png", "SIJA — Angkatan 49", "Network Engineer", "Praktik jaringan dan proyek selama di SIJA membuat saya lebih memahami bagaimana teknologi digunakan di dunia kerja. Saya jadi lebih percaya diri untuk mengembangkan karier di bidang IT."]] as const;

function Label({ children }: { children: string }) { return <span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase tracking-[.04em] text-[#ff7a00] shadow-[0_2px_8px_rgba(15,23,42,.08)]">{children}</span>; }

export function SijaPage() {
  return <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]"><PublicNavbar /><main>
    <section className="relative isolate min-h-[620px] overflow-hidden bg-[#c7b8ac] pt-24 sm:min-h-[700px] lg:min-h-[760px] lg:pt-32"><img className="absolute inset-0 -z-10 size-full object-cover object-center" src={asset("Hero Section (5).png")} alt="Siswa Sistem Informasi, Jaringan dan Aplikasi" /><div className="mx-auto flex w-full max-w-[1272px] px-5 pb-36 sm:px-8 lg:px-16 lg:pb-44"><div className="max-w-[560px] pt-10 text-white sm:pt-16 lg:pt-20"><Label>JURUSAN SIJA</Label><h1 className="mt-4 text-[34px] font-bold leading-[1.08] sm:text-5xl lg:text-[60px]">Sistem Informasi, <span className="text-[#ff8a00]">Jaringan &amp; Aplikasi</span></h1><p className="mt-4 max-w-[480px] text-sm leading-5 text-white/90 sm:text-base sm:leading-6">Membekali siswa dengan keterampilan teknologi informasi melalui pengembangan aplikasi, pengelolaan jaringan, sistem informasi, dan solusi digital yang dekat dengan kebutuhan industri.</p></div></div></section>
    <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#ff8414] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["4 Tahun", "Program Pendidikan"], ["30+", "Mitra Industri"], ["288+", "Siswa"], ["50+", "Prestasi SIJA"]].map(([value, label]) => <div className="border-r border-white/40 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
    <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 3 (4).png")} alt="Siswa Sistem Informasi, Jaringan dan Aplikasi" /><div><Label>MENGENAL SIJA</Label><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Mengenal <span className="text-[#ff7a00]">Sistem Informasi, Jaringan &amp; Aplikasi</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">SIJA membekali siswa dengan keterampilan mengembangkan aplikasi, mengelola jaringan, dan membangun sistem informasi melalui pembelajaran teori dan praktik dengan mengutamakan ketelitian, kreativitas, dan pemecahan masalah.</p><p className="mt-3 text-sm font-bold text-[#ff7a00]">Membangun solusi digital dari ide menjadi nyata.</p></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>KOMPETENSI UTAMA</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Kompetensi yang <span className="text-[#ff7a00]">Dipelajari</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Siswa SIJA mengembangkan keterampilan pemrograman, jaringan, basis data, sistem informasi, dan pengembangan aplikasi melalui teori serta proyek.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{competencies.map((item) => <div className="flex items-center gap-2 rounded-xl bg-white px-3 py-3 text-left text-[11px] font-semibold shadow-[0_3px_12px_rgba(15,23,42,.05)] sm:text-xs" key={item}><img className="size-7 shrink-0 rounded-full" src={asset("Button shortcut (4).png")} alt="" aria-hidden="true" />{item}</div>)}</div></div></section>
    <section className="px-5 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>ROADMAP PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari Dasar hingga Siap Berkarya <span className="text-[#ff7a00]">#Program4Tahun</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Empat tahun perjalanan untuk mengenal, mengembangkan, menerapkan, dan menguji kompetensi teknologi informasi di dunia industri.</p><img className="mx-auto mt-8 w-full max-w-[1140px] object-contain" src={asset("Roadmap Jurusan.png")} alt="Roadmap pembelajaran SIJA" /></div></section>
    <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1200px] text-center"><Label>KEGIATAN PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Belajar Tidak Hanya di <span className="text-[#ff7a00]">Dalam Kelas</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Pengalaman belajar SIJA hadir melalui perpaduan teori, praktik, proyek, dan kegiatan yang membantu siswa memahami teknologi digital secara langsung.</p><div className="mx-auto mt-8 grid max-w-[1100px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (9).png")} alt="Dokumentasi pembelajaran SIJA baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (10).png")} alt="Dokumentasi pembelajaran SIJA baris kedua" /></div></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>PRESTASI SISWA</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Prestasi yang Dibangun <span className="text-[#ff7a00]">dari Kompetensi</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Kompetensi yang dipelajari menjadi bekal siswa SIJA untuk berkompetisi, berinovasi, dan menunjukkan kemampuan di bidang teknologi informasi.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{achievements.map(([name, achievement, photo]) => <article className="overflow-hidden rounded-2xl bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={name}><img className="aspect-[1.15] w-full object-cover" src={asset(photo)} alt={name} /><div className="p-3"><h3 className="text-xs font-bold text-[#ff7a00]">{name}</h3><p className="mt-1 text-[10px] leading-4 text-[#61708b]">{achievement}</p></div></article>)}</div></div></section>
    <IndustryPartnersMarquee accent="text-[#ff7a00]" />
    <section className="bg-[#ff8414] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><Label>ALUMNI SIJA</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari SIJA, Melangkah Lebih Jauh</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Kompetensi yang diperoleh selama belajar menjadi bekal alumni untuk memasuki dunia industri teknologi, melanjutkan pendidikan, maupun mengembangkan karier di bidang digital.</p><div className="mx-auto mt-8 grid max-w-[1080px] gap-5 sm:grid-cols-2">{alumni.map(([name, photo, batch, work, quote]) => <article className="flex items-start gap-4 rounded-2xl bg-white p-4 text-left text-[#10182b] sm:gap-5 sm:p-5" key={name}><img className="size-28 shrink-0 rounded-xl object-cover sm:size-36" src={asset(photo)} alt={name} /><div className="min-w-0"><strong className="block text-base sm:text-lg">{name}</strong><span className="mt-1 block text-xs text-[#61708b] sm:text-sm">{batch}</span><strong className="mt-2 block text-xs text-[#ff7a00] sm:text-sm">{work}</strong><p className="mt-2 text-xs leading-5 text-[#61708b] sm:text-sm">“{quote}”</p></div></article>)}</div></section>
  </main><PublicFooter /></div>;
}
