import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";
import { IndustryPartnersMarquee } from "../components/public/IndustryPartnersMarquee";

const asset = (name: string) => `/assets/figma/TFLM/${name}`;
const competencies = ["Gambar Teknik", "Pengukuran & Material", "Pemotongan Logam", "Pembentukan Logam", "Pengelasan", "Permesinan", "Fabrikasi & Manufaktur", "K3 & Quality Control"];
const achievements = [["Raihan Nugroho", "Juara 1 - Kompetisi Pengelasan Pelajar", "Raihan Nugroho.png"], ["Salsa Nurfatiha", "Juara 2 - Lomba Fabrikasi Logam", "Salsa Nurfatiha.png"], ["Riky Hamdan", "Finalis - Kompetisi Manufaktur Pelajar", "Riky Hamdan.png"], ["Nayla Safira", "Juara 3 - Kompetisi Teknik Mesin", "Nayla Safira.png"]] as const;
const alumni = [["Raka Pratama", "Raka Pratama.png", "TFLM — Angkatan 50", "Bekerja sebagai Welder di Industri Manufaktur", "Selama belajar di TFLM, saya terbiasa bekerja dengan alat, material, dan mesin secara langsung. Pengalaman praktik membuat saya lebih percaya diri ketika menghadapi pekerjaan di dunia industri."], ["Abdusallam", "Abdusallam.png", "TFLM — Angkatan 49", "Melanjutkan Pendidikan — Teknik Mesin", "TFLM mengajarkan saya untuk bekerja dengan teliti dan disiplin. Pengalaman membaca gambar teknik dan mengerjakan proyek praktik menjadi bekal yang sangat membantu ketika melanjutkan pendidikan."]] as const;

function Label({ children }: { children: string }) { return <span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase tracking-[.04em] text-[#d40009] shadow-[0_2px_8px_rgba(15,23,42,.08)]">{children}</span>; }

export function TflmPage() {
  return (
    <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]"><PublicNavbar /><main>
      <section className="relative isolate min-h-[620px] overflow-hidden bg-[#c5b7ba] pt-24 sm:min-h-[700px] lg:min-h-[760px] lg:pt-32"><img className="absolute inset-0 -z-10 size-full object-cover object-center" src={asset("Hero Section (2).png")} alt="Siswa Teknik Fabrikasi Logam dan Manufaktur" /><div className="mx-auto flex w-full max-w-[1272px] px-5 pb-36 sm:px-8 lg:px-16 lg:pb-44"><div className="max-w-[560px] pt-10 text-white sm:pt-16 lg:pt-20"><Label>JURUSAN TFLM</Label><h1 className="mt-4 text-[34px] font-bold leading-[1.08] sm:text-5xl lg:text-[60px]">Teknik Fabrikasi <span className="text-[#e30613]">Logam &amp; Manufaktur</span></h1><p className="mt-4 max-w-[480px] text-sm leading-5 text-white/90 sm:text-base sm:leading-6">Membekali siswa dengan keterampilan fabrikasi logam dan manufaktur melalui pembelajaran berbasis praktik, teknologi, dan proyek nyata yang dekat dengan kebutuhan industri.</p></div></div></section>
      <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#d40009] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["4 Tahun", "Program Pendidikan"], ["10+", "Mitra Industri"], ["288+", "Siswa"], ["17+", "Prestasi TFLM"]].map(([value, label]) => <div className="border-r border-white/40 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
      <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 3 (2).png")} alt="Siswa Teknik Fabrikasi Logam dan Manufaktur" /><div><Label>MENGENAL TFLM</Label><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Mengenal <span className="text-[#d40009]">Teknik Fabrikasi Logam &amp; Manufaktur</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">TFLM membekali siswa dengan keterampilan mengolah, membentuk, memotong, dan menyambung logam melalui pembelajaran teori dan praktik. Siswa dibiasakan bekerja teliti, disiplin, dan mengutamakan keselamatan dalam setiap proses kerja.</p><p className="mt-3 text-sm font-bold text-[#d40009]">Mengolah logam menjadi karya yang bernilai.</p></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>KOMPETENSI UTAMA</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Kompetensi yang <span className="text-[#d40009]">Dipelajari</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Siswa TFLM mengembangkan keterampilan fabrikasi logam dan manufaktur melalui proses perencanaan, pengerjaan, pengujian, hingga penyelesaian produk dengan mengutamakan keselamatan kerja.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{competencies.map((item) => <div className="flex items-center gap-2 rounded-xl bg-white px-3 py-3 text-left text-[11px] font-semibold shadow-[0_3px_12px_rgba(15,23,42,.05)] sm:text-xs" key={item}><img className="size-7 shrink-0 rounded-full" src={asset("Button shortcut (2).png")} alt="" aria-hidden="true" />{item}</div>)}</div></div></section>
      <section className="px-5 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>ROADMAP PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari Dasar hingga Siap Berkarya <span className="text-[#d40009]">#Program4Tahun</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Empat tahun perjalanan untuk mengenal dasar fabrikasi, mengembangkan keterampilan, dan menerapkan kompetensi melalui pengalaman di dunia industri.</p><img className="mx-auto mt-8 w-full max-w-[1140px] object-contain" src={asset("Frame 36434 (3).png")} alt="Roadmap pembelajaran TFLM" /></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1200px] text-center"><Label>KEGIATAN PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Belajar Tidak Hanya di <span className="text-[#d40009]">Dalam Kelas</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Pengalaman belajar TFLM hadir melalui perpaduan teori, praktik, proyek, dan kegiatan yang membantu siswa memahami proses kerja manufaktur secara langsung.</p><div className="mx-auto mt-8 grid max-w-[1100px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (5).png")} alt="Dokumentasi pembelajaran TFLM baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (6).png")} alt="Dokumentasi pembelajaran TFLM baris kedua" /></div></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>PRESTASI SISWA</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Prestasi yang Dibangun <span className="text-[#d40009]">dari Kompetensi</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Keterampilan yang diperoleh melalui praktik menjadi bekal siswa TFLM untuk berkompetisi, menghasilkan karya, dan menunjukkan kemampuan di bidang fabrikasi serta manufaktur.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{achievements.map(([name, achievement, photo]) => <article className="overflow-hidden rounded-2xl bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={name}><img className="aspect-[1.15] w-full object-cover" src={asset(photo)} alt={name} /><div className="p-3"><h3 className="text-xs font-bold text-[#d40009]">{name}</h3><p className="mt-1 text-[10px] leading-4 text-[#61708b]">{achievement}</p></div></article>)}</div></div></section>
      <IndustryPartnersMarquee accent="text-[#d40009]" />
      <section className="bg-[#d40009] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><Label>ALUMNI TFLM</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari TFLM, Melangkah Lebih Jauh</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Kompetensi yang diperoleh selama belajar menjadi bekal alumni untuk memasuki dunia industri, melanjutkan pendidikan, maupun mengembangkan karier di bidang fabrikasi dan manufaktur.</p><div className="mx-auto mt-8 grid max-w-[1080px] gap-5 sm:grid-cols-2">{alumni.map(([name, photo, batch, work, quote]) => <article className="flex items-start gap-4 rounded-2xl bg-white p-4 text-left text-[#10182b] sm:gap-5 sm:p-5" key={name}><img className="size-28 shrink-0 rounded-xl object-cover sm:size-36" src={asset(photo)} alt={name} /><div className="min-w-0"><strong className="block text-base sm:text-lg">{name}</strong><span className="mt-1 block text-xs text-[#61708b] sm:text-sm">{batch}</span><strong className="mt-2 block text-xs text-[#d40009] sm:text-sm">{work}</strong><p className="mt-2 text-xs leading-5 text-[#61708b] sm:text-sm">“{quote}”</p></div></article>)}</div></section>
    </main><PublicFooter /></div>
  );
}
