import { useRef } from "react";

import { figmaAssets } from "../assets/figmaAssets";
import { IndustryPartnersMarquee } from "../components/public/IndustryPartnersMarquee";
import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";

const asset = (name: string) => `/assets/figma/TKR/${name}`;
const competencies = ["Dasar Otomotif", "Perawatan Mesin", "Perbaikan Mesin", "Kelistrikan Kendaraan", "Sistem Pemindah Tenaga", "Sistem Sasis", "Diagnosis Kendaraan", "K3 & Budaya Kerja"];
const achievements = [["Raka Kuncoro", "Juara 1 - Kompetisi Automotive Skill", "Raka Kuncoro.png"], ["Putri Cantika", "Juara 2 - Lomba Kompetensi Otomotif", "Putri Cantika.png"], ["Kaesar Agung", "Finalis - Automotive Technology", "Kaesar Agung.png"], ["Eva Khuzaifah", "Juara 3 - Kompetisi Teknik Kendaraan", "Eva Khuzaifah.png"]] as const;
const alumni = [["Rizky Aditya", "Rizky Aditya.png", "TKR — Angkatan 50", "Automotive Technician", "Praktik di TKR membuat saya terbiasa menangani kendaraan secara langsung. Dari pemeriksaan sampai troubleshooting, pengalaman itu menjadi bekal penting ketika mulai bekerja di industri otomotif."], ["Dwi Bakti", "Dwi Bakti.png", "TKR — Angkatan 50", "Melanjutkan Pendidikan — Teknik Otomotif", "Di TKR saya belajar memahami kendaraan bukan hanya dari teori, tetapi juga dari praktik. Pengalaman tersebut membuat saya lebih percaya diri untuk melanjutkan pendidikan di bidang otomotif."]] as const;

function Label({ children }: { children: string }) { return <span className="inline-flex items-center gap-1.5 rounded-full bg-[#eeeeee] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.04em] text-[#575757] shadow-[0_2px_8px_rgba(15,23,42,.08)]"><span className="size-1.5 rounded-full bg-[#575757]" aria-hidden="true" />{children}</span>; }

export function TkrPage() {
  const alumniTrackRef = useRef<HTMLDivElement>(null);
  function scrollAlumni(direction: number) { alumniTrackRef.current?.scrollBy({ left: direction * (alumniTrackRef.current?.clientWidth ?? 0) * 0.6, behavior: "smooth" }); }

  return <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]"><PublicNavbar /><main className="[&>section:nth-of-type(3)]:bg-white">
    <section className="relative isolate w-full overflow-hidden bg-[#9a9a9a]"><div className="relative mx-auto aspect-[1440/650] min-h-[540px] w-full sm:min-h-[580px] lg:min-h-0"><img className="absolute inset-0 z-0 size-full object-cover object-[68%_center] sm:object-[78%_center] lg:object-center" src={asset("Hero Section (3).png")} alt="Siswa Teknik Kendaraan Ringan" /><div className="relative z-10 mx-auto flex h-full w-[calc(100%-32px)] max-w-[1272px] items-start pl-5 pr-4 pt-[132px] sm:pl-7 sm:pr-6 sm:pt-[176px] lg:pt-[192px]"><div className="max-w-[700px] text-white"><Label>JURUSAN TKR</Label><h1 className="mt-4 text-[34px] font-bold leading-[1.08] sm:text-5xl lg:text-[56px] xl:text-[60px]">Teknik Kendaraan <span className="text-[#888888]">Ringan</span></h1><p className="mt-4 max-w-[700px] text-sm leading-5 text-white/90 sm:text-base sm:leading-6">Membekali siswa dengan keterampilan perawatan, perbaikan, dan diagnosis kendaraan ringan melalui pembelajaran berbasis praktik serta teknologi otomotif.</p></div></div></div></section>
    <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#575757] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["3 Tahun", "Program Pendidikan"], ["10+", "Mitra Industri"], ["288+", "Siswa"], ["20+", "Prestasi TKR"]].map(([value, label]) => <div className="border-r border-white/40 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
    <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 3 (3).png")} alt="Siswa Teknik Kendaraan Ringan" /><div><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Mengenal<br /><span className="text-[#575757]">Teknik Kendaraan Ringan</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">TKR membekali siswa dengan pengetahuan dan keterampilan dalam merawat, memperbaiki, serta mendiagnosis sistem kendaraan ringan. Pembelajaran memadukan teori dan praktik agar siswa mengenal komponen kendaraan, melakukan servis, dan menganalisis gangguan kendaraan dengan mengutamakan keselamatan kerja.</p><p className="mt-3 text-sm font-bold text-[#575757]">Mengenal mesin, memahami sistem, siap memperbaiki.</p></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>KOMPETENSI UTAMA</Label><h2 className="mt-4 text-[26px] font-bold sm:text-[34px]">Kompetensi <span className="text-[#575757]">yang Dipelajari</span></h2><p className="mx-auto mt-3 max-w-[760px] text-sm leading-6 text-[#61708b] sm:text-base sm:leading-7">Siswa TKR mengembangkan keterampilan otomotif melalui pemeriksaan, perawatan, perbaikan, dan diagnosis berbagai sistem kendaraan.</p><div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-4">{competencies.map((item) => <div className="flex items-center gap-3 rounded-2xl bg-white px-4 py-4 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)] sm:px-5" key={item}><img className="size-10 shrink-0 rounded-full sm:size-11" src={asset("Button shortcut (3).png")} alt="" aria-hidden="true" /><span className="text-sm font-medium leading-tight sm:text-base">{item}</span></div>)}</div></div></section>
    <section className="px-5 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>ROADMAP PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari Dasar hingga Siap Berkarya <span className="text-[#575757]">#Program3Tahun</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-[#61708b]">Tiga tahun perjalanan untuk mengenal teknologi kendaraan, menguasai keterampilan perawatan dan perbaikan, hingga menerapkannya melalui pengalaman di dunia industri.</p><img className="mx-auto mt-8 w-full max-w-[1140px] object-contain" src={asset("Frame 36434 (4).png")} alt="Roadmap pembelajaran TKR" /></div></section>
    <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1200px] text-center"><Label>KEGIATAN PEMBELAJARAN</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Belajar Tidak Hanya di <span className="text-[#575757]">Dalam Kelas</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Pengalaman belajar TKR hadir melalui perpaduan teori, praktik, proyek, dan kegiatan yang membantu siswa memahami teknologi kendaraan secara nyata.</p><div className="mx-auto mt-8 grid max-w-[1100px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (7).png")} alt="Dokumentasi pembelajaran TKR baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (8).png")} alt="Dokumentasi pembelajaran TKR baris kedua" /></div></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><Label>CIRI KHAS TKR</Label></div><div className="mx-auto mt-8 grid max-w-[1140px] items-center gap-8 sm:gap-12 lg:grid-cols-2"><div className="text-left"><h2 className="text-[26px] font-bold leading-[1.15] sm:text-[34px]">Identitas <span className="text-[#575757]">Teknik Kendaraan Ringan #Wearpack</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base sm:leading-7">Identitas TKR tercermin dari kebiasaan siswa bekerja secara teliti, disiplin, dan bertanggung jawab. Praktik pemeriksaan, perawatan, dan perbaikan kendaraan membentuk karakter yang mengutamakan keselamatan serta ketepatan dalam setiap diagnosis.</p></div><img className="mx-auto w-full max-w-[460px] object-contain" src={asset("image 3 (3).png")} alt="Identitas siswa TKR dengan wearpack" /></div></section>
    <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1200px] text-center"><Label>PRESTASI SISWA</Label><h2 className="mt-4 text-[26px] font-bold sm:text-[34px]">Prestasi yang Dibangun <span className="text-[#575757]">dari Kompetensi</span></h2><p className="mx-auto mt-3 max-w-[760px] text-sm leading-6 text-[#61708b] sm:text-base sm:leading-7">Keterampilan yang diperoleh melalui praktik menjadi bekal siswa TKR untuk berkompetisi, berinovasi, dan menunjukkan kemampuan di bidang otomotif.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{achievements.map(([name, achievement, photo]) => <article className="overflow-hidden rounded-[20px] bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={name}><img className="w-full object-cover" src={asset(photo)} alt={name} /><div className="p-4"><h3 className="text-base font-bold text-[#575757]">{name}</h3><span className="mt-1 block h-[3px] w-[48px] rounded-full bg-[#575757]" aria-hidden="true" /><p className="mt-2 text-sm leading-5 text-[#10182b]">{achievement}</p></div></article>)}</div></div></section>
    <IndustryPartnersMarquee accent="text-[#575757]" barClass="bg-[#575757]" labelClass="bg-[#eeeeee] text-[#575757]" stats={[["8+", "Mitra Industri"], ["12+", "Program Kolaborasi"], ["20+", "Kegiatan Industri"]]} />
    <section className="bg-[linear-gradient(90deg,#777777,#575757_50%,#333333)] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><Label>ALUMNI TKR</Label><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Dari TKR, Melangkah Lebih Jauh</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Kompetensi yang diperoleh selama belajar menjadi bekal alumni untuk memasuki dunia industri otomotif, melanjutkan pendidikan, maupun mengembangkan karier di bidang kendaraan ringan.</p><div className="mx-auto mt-8 flex max-w-[1200px] items-center gap-3 sm:gap-5"><button type="button" onClick={() => scrollAlumni(-1)} aria-label="Alumni sebelumnya" className="group hidden size-11 shrink-0 cursor-pointer place-items-center rounded-full bg-white shadow-[0_4px_15px_rgba(0,0,0,.2)] transition hover:bg-[#575757] md:grid"><img className="size-5 transition-[filter] group-hover:brightness-0 group-hover:invert" src={figmaAssets.advantages.arrowLeft} alt="" /></button><div ref={alumniTrackRef} className="flex min-w-0 flex-1 gap-5 overflow-x-auto pb-1 [scrollbar-width:none] [touch-action:pan-y] [&::-webkit-scrollbar]:hidden">{alumni.map(([name, photo, batch, work, quote]) => <article className="flex w-[85%] shrink-0 items-start gap-4 rounded-2xl bg-white p-4 text-left text-[#10182b] sm:gap-5 sm:p-5 md:w-[calc(50%-10px)]" key={name}><img className="size-28 shrink-0 rounded-xl object-cover sm:size-36" src={asset(photo)} alt={name} /><div className="min-w-0"><strong className="block text-base sm:text-lg">{name}</strong><span className="mt-1 block text-xs text-[#61708b] sm:text-sm">{batch}</span><strong className="mt-2 block text-xs text-[#575757] sm:text-sm">{work}</strong><p className="mt-2 text-xs leading-5 text-[#61708b] sm:text-sm">“{quote}”</p></div></article>)}</div><button type="button" onClick={() => scrollAlumni(1)} aria-label="Alumni berikutnya" className="group hidden size-11 shrink-0 cursor-pointer place-items-center rounded-full bg-white shadow-[0_4px_15px_rgba(0,0,0,.2)] transition hover:bg-[#575757] md:grid"><img className="size-5 transition-[filter] group-hover:brightness-0 group-hover:invert" src={figmaAssets.advantages.arrowRight} alt="" /></button></div></section>
  </main><PublicFooter /></div>;
}
