import { PublicFooter } from "../components/public/PublicFooter";
import { PublicNavbar } from "../components/public/PublicNavbar";

const asset = (name: string) => `/assets/figma/BLUD-UPTECHNO/${name}`;

const services = [
  ["Elektronika", "Penerapan dan pengembangan solusi berbasis perangkat elektronika."],
  ["Komunikasi", "Penerapan teknologi komunikasi dan perangkat pendukungnya."],
  ["Teknologi & Komputasi", "Pengembangan solusi teknologi sesuai kebutuhan pengguna."],
  ["Perakitan & Perawatan", "Perakitan, pengujian, dan pemeliharaan perangkat teknologi."],
] as const;

const projects = [
  ["Smart Line Follower", "Smart Line Follower.png"],
  ["Electronic Circuit", "Electronic Circuit.png"],
  ["MikroTik Network", "MikroTik Network .png"],
  ["CCTV Security System", "CCTV Security System.png"],
] as const;

export function UptechnoPage() {
  return (
    <div className="min-h-screen overflow-x-clip bg-[#f3f7ff] text-[#10182b]
      "><PublicNavbar /><main>
      <section className="relative isolate min-h-[620px] overflow-hidden bg-[#9cb3cb] pt-24 sm:min-h-[700px] lg:min-h-[760px] lg:pt-32"><img className="absolute inset-0 -z-10 size-full object-cover object-center" src={asset("BG Hero.png")} alt="UPTECHNO SMKN 26 Jakarta" /><div className="mx-auto flex w-full max-w-[1272px] px-5 pb-36 sm:px-8 lg:px-16 lg:pb-44"><div className="max-w-[560px] pt-10 text-white sm:pt-16 lg:pt-20"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc]">BLUD • UNIT PRODUKSI &amp; LAYANAN</span><h1 className="mt-4 text-5xl font-bold leading-tight">UP<span className="text-[#0876e7]">TECHNO</span></h1><p className="mt-4 max-w-[480px] text-sm leading-6 text-white/90 sm:text-base">UPTECHNO merupakan unit produksi dan layanan berbasis kompetensi Teknik Elektronika &amp; Komunikasi, yang dikelola oleh siswa untuk menerapkan keterampilan teknologi melalui pengalaman nyata.</p></div></div></section>
      <section className="relative z-20 mx-auto -mt-8 w-[calc(100%-32px)] max-w-[1200px] overflow-hidden rounded-lg bg-[#006cdc] text-center text-white shadow-[0_8px_24px_rgba(15,23,42,.18)] sm:-mt-10"><div className="grid grid-cols-2 sm:grid-cols-4">{[["150+", "Siswa Terlibat"], ["35+", "Client"], ["70+", "Project"], ["12+", "Jenis Layanan"]].map(([value, label]) => <div className="border-r border-dashed border-white/60 px-2 py-3 last:border-0 sm:py-4" key={label}><strong className="block text-xl font-bold sm:text-2xl">{value}</strong><span className="text-[9px] sm:text-xs">{label}</span></div>)}</div></section>
      <section className="mx-auto grid max-w-[1200px] items-center gap-8 px-6 py-14 sm:px-10 md:grid-cols-[.9fr_1.1fr] lg:py-20"><img className="mx-auto w-full max-w-[470px] object-contain" src={asset("image 4.png")} alt="Siswa UPTECHNO mengerjakan proyek teknologi" /><div><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc] shadow-sm">TENTANG UPTECHNO</span><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Tentang <span className="text-[#006cdc]">UPTECHNO</span></h2><p className="mt-4 text-sm leading-6 text-[#61708b] sm:text-base">UPTECHNO adalah unit produksi dan layanan yang menjadi ruang bagi siswa Teknik Elektronika &amp; Komunikasi untuk menerapkan kompetensi yang mereka pelajari melalui pekerjaan dan proyek nyata.</p><p className="mt-3 text-sm leading-6 text-[#61708b] sm:text-base">Di UPTECHNO, siswa tidak hanya belajar memahami teknologi, tetapi juga belajar bagaimana merancang, mengembangkan, menguji, dan memberikan solusi sesuai kebutuhan.</p></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc] shadow-sm">LAYANAN &amp; PRODUK</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Layanan <span className="text-[#006cdc]">UPTECHNO</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Berbagai layanan berbasis elektronika, teknologi, dan komunikasi yang dikerjakan langsung oleh siswa Teknik Elektronika &amp; Komunikasi.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{services.map(([title, copy]) => <article className="flex gap-3 rounded-2xl bg-white p-5 text-left shadow-[0_4px_16px_rgba(15,23,42,.05)]" key={title}><img className="size-9 shrink-0 rounded-full" src={asset("Button shortcut.png")} alt="" aria-hidden="true" /><div><h3 className="text-lg font-bold text-[#006cdc]">{title}</h3><p className="mt-1 text-xs leading-5 text-[#61708b]">{copy}</p></div></article>)}</div></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc] shadow-sm">ALUR LAYANAN</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Bagaimana <span className="text-[#006cdc]">UPTECHNO</span> Bekerja?</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">UPTECHNO mengubah kebutuhan menjadi solusi melalui proses yang terarah, mulai dari konsultasi hingga penyelesaian.</p><img className="mx-auto mt-8 hidden w-full object-contain md:block" src={asset("Alur BLUD (1).png")} alt="Alur layanan UPTECHNO" /><div className="mt-8 grid gap-4 text-left md:hidden">{["Perencanaan", "Analisis Kebutuhan", "Pengembangan", "Pengujian", "Penyelesaian"].map((step, index) => <div className="rounded-2xl bg-white p-4" key={step}><strong className="text-[#006cdc]">0{index + 1} — {step}</strong></div>)}</div></div></section>
      <section className="px-6 py-14 sm:px-10 lg:py-20"><div className="mx-auto max-w-[1140px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc] shadow-sm">KARYA &amp; PORTOFOLIO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Karya Teknologi <span className="text-[#006cdc]">UPTECHNO</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Dari ide, eksperimen, hingga menjadi solusi teknologi yang dapat digunakan.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{projects.map(([title, photo]) => <article className="overflow-hidden rounded-2xl bg-white text-left shadow-[0_4px_16px_rgba(15,23,42,.06)]" key={title}><img className="aspect-square w-full object-cover" src={asset(photo)} alt={title} /><div className="p-3"><h3 className="text-xs font-bold text-[#006cdc]">{title}</h3><p className="mt-1 text-[10px] text-[#61708b]">UPTECHNO • TEK</p></div></article>)}</div></div></section>
      <section className="px-5 py-12 sm:px-10 lg:py-16"><div className="mx-auto max-w-[1100px] text-center"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc] shadow-sm">DI BALIK UPTECHNO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Di Balik <span className="text-[#006cdc]">Setiap Karya</span></h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#61708b]">Melihat proses siswa TEK belajar, bereksperimen, dan mengembangkan solusi teknologi.</p><div className="mx-auto mt-8 grid max-w-[1000px] gap-3"><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (11).png")} alt="Kegiatan UPTECHNO baris pertama" /><img className="h-auto w-full rounded-2xl object-contain" src={asset("Dokumentasi Pembelajaran (12).png")} alt="Kegiatan UPTECHNO baris kedua" /></div></div></section>
      <section className="bg-[#006cdc] px-6 py-14 text-center text-white sm:px-10 lg:py-16"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase text-[#006cdc]">KONTAK UPTECHNO</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Punya Kebutuhan di Bidang Teknologi?</h2><p className="mx-auto mt-3 max-w-xl text-sm text-white/90">Bersama UPTECHNO, wujudkan kebutuhan teknologi menjadi solusi yang dikerjakan langsung oleh siswa TEK.</p><a className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-xs font-bold text-[#006cdc]" href="https://wa.me/6285212588797" target="_blank" rel="noreferrer"><img className="size-4 object-contain" src={asset("basil_whatsapp-solid (1).png")} alt="" aria-hidden="true" />Hubungi UPTECHNO</a></section>
    </main><PublicFooter /></div>
  );
}
