import { useEffect, useState } from 'react';
import { PortalLayout } from '../../../layouts/PortalLayout';
import { RequirePermission } from '../../auth/RequireAuth';
import { generatePractice, getLearningSummary } from '../learning.api';
import type { LearningSummary, TopicRecommendation } from '../learning.types';

const statusLabel: Record<string, string> = { MASTERED: 'Sudah dikuasai', ON_TRACK: 'Sesuai target', NEEDS_ATTENTION: 'Perlu perhatian', NOT_ENOUGH_DATA: 'Data belum cukup' };
export function LearningRecommendationPage() {
  const [data, setData] = useState<LearningSummary | null>(null); const [error, setError] = useState(''); const [practice, setPractice] = useState<{ topic: TopicRecommendation; explanation: string; questions: string[] } | null>(null); const [busy, setBusy] = useState('');
  useEffect(() => { getLearningSummary().then(setData).catch((e) => setError(e.message)); }, []);
  async function openPractice(topic: TopicRecommendation) { setBusy(topic.topicId); try { const result = await generatePractice(topic.topicId); setPractice({ topic, explanation: result.explanation, questions: result.questions }); } catch (e) { setError(e instanceof Error ? e.message : 'Latihan tidak tersedia.'); } finally { setBusy(''); } }
  return <RequirePermission permission="student:learning"><PortalLayout><p className="text-sm font-medium text-primary">Belajar berbasis data penilaian</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Rekomendasi Belajar</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted">Rekomendasi dihitung dari assessment yang tercatat, bukan prediksi AI.</p>{error && <p className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{practice && <section className="mt-8 rounded-[24px] border border-primary/20 bg-white p-6 shadow-[0_4px_16px_rgba(15,23,42,.06)]"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-light-blue px-3 py-1.5 text-xs font-medium text-primary-dark">AI-generated practice</span><h2 className="mt-4 text-xl font-bold text-ink">Latihan: {practice.topic.topicName}</h2></div><button className="text-sm font-medium text-muted" onClick={() => setPractice(null)}>Tutup</button></div><p className="mt-4 text-sm leading-7 text-muted">{practice.explanation}</p>{practice.questions.length > 0 && <ol className="mt-4 grid gap-3 pl-5 text-sm leading-6 text-ink">{practice.questions.map((question) => <li key={question}>{question}</li>)}</ol>}<p className="mt-5 text-xs text-muted">Latihan ini adalah bantuan belajar AI, bukan penilaian guru dan tidak mengubah nilai Anda.</p></section>}{!data && !error && <LearningSkeleton />}{data && <><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Mata pelajaran dengan data" value={data.summary.assessedSubjects} /><Metric label="Topik perlu perhatian" value={data.summary.needsAttention} /><Metric label="Topik sudah sesuai" value={data.summary.mastered} /></div>{!data.subjects.length && <div className="mt-8 rounded-[24px] border border-light-blue bg-white p-8 text-center text-muted">Belum ada data penilaian yang cukup untuk membuat rekomendasi.</div>}<div className="mt-8 grid gap-5 lg:grid-cols-2">{data.subjects.map((subject) => <article key={subject.id} className="rounded-[24px] border border-light-blue bg-white p-6 shadow-[0_4px_16px_rgba(15,23,42,.06)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.14em] text-primary">{subject.code}</p><h2 className="mt-2 text-xl font-bold text-ink">{subject.name}</h2></div><span className="rounded-full bg-light-blue px-3 py-1.5 text-xs font-medium text-primary-dark">{statusLabel[subject.status]}</span></div><div className="mt-5 grid gap-3">{subject.topics.map((topic) => <TopicRow key={topic.topicId} topic={topic} onPractice={() => void openPractice(topic)} busy={busy === topic.topicId} />)}</div></article>)}</div></>}</PortalLayout></RequirePermission>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-light-blue bg-white p-5"><p className="text-2xl font-bold text-primary-dark">{value}</p><p className="mt-2 text-sm leading-5 text-muted">{label}</p></div>; }
function LearningSkeleton() { return <div className="mt-8 grid gap-5 lg:grid-cols-2" aria-label="Memuat rekomendasi"><div className="h-44 animate-pulse rounded-[24px] bg-white/70" /><div className="h-44 animate-pulse rounded-[24px] bg-white/70" /></div>; }
function TopicRow({ topic, onPractice, busy }: { topic: TopicRecommendation; onPractice: () => void; busy: boolean }) { const progress = topic.averageScore === null ? 0 : Math.min(100, topic.averageScore); const statusClass = topic.status === 'NEEDS_ATTENTION' ? 'bg-[#fff4df] text-[#9b6500]' : topic.status === 'MASTERED' ? 'bg-[#e9f8f1] text-[#18794e]' : 'bg-light-blue text-primary-dark'; return <div className="rounded-2xl border border-white bg-school-bg/75 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-ink">{topic.topicName}</strong><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusClass}`}>{statusLabel[topic.status]}</span></div>{topic.averageScore !== null && <div className="mt-4"><div className="flex justify-between text-xs font-medium text-muted"><span>{topic.averageScore.toFixed(1)}%</span><span>Target {topic.targetScore?.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white"><div className={`h-full rounded-full ${topic.status === 'NEEDS_ATTENTION' ? 'bg-[#e2a82e]' : 'bg-primary'}`} style={{ width: `${progress}%` }} /></div></div>}<p className="mt-3 text-sm text-muted">{topic.averageScore === null ? 'Belum ada nilai tercatat.' : `Gap ${topic.gap?.toFixed(1)} poin · ${topic.assessmentCount} assessment`}</p>{topic.approvedResources.length > 0 && <div className="mt-3 border-t border-white pt-3"><p className="text-xs font-bold uppercase tracking-[.12em] text-muted">Sumber disetujui</p><ul className="mt-2 grid gap-1 text-sm">{topic.approvedResources.map((resource) => <li key={resource.id}>{resource.url ? <a className="font-medium text-primary hover:underline" href={resource.url} target="_blank" rel="noreferrer">{resource.title}</a> : <span className="font-medium text-ink">{resource.title}</span>}</li>)}</ul></div>}{topic.status === 'NEEDS_ATTENTION' && <button onClick={onPractice} disabled={busy} className="mt-4 rounded-full bg-gradient-to-br from-primary-dark via-primary to-soft-blue px-4 py-2 text-xs font-medium text-white disabled:opacity-60">{busy ? 'Menyiapkan...' : 'Latihan dengan AI'}</button>}</div>; }
